### ISSUE TITLE
Experiments images are not displayed on Facebook and Activity Stream one is not displayed on Twitter

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2473] opened 2017-05-25 16:42 UTC
**[Affected versions]:**
- Firefox 53.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- A Facebook and a Twitter profile was already logged on the used profile. 

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Click on one of the active experiments cards and after redirected, copy the page URL.
3. In two new tabs, navigate to "https://www.facebook.com" and "https://twitter.com" pages.
4. Paste the copied URL in the Facebook message box and "Post" it.
5. Paste the same URL in the Twitter message box and "Tweet" it.
6. Observe both the posted messages on the social platforms.

**[Expected result]:**
- Both the social platforms are displaying an image specific to the experiment in the message.

**[Actual result]:**
- Twitter correctly shows the experiment image (except Activity Stream), while Facebook displays the default Test Pilot logo image.

**[Notes]**
- This issue occurs for all the experiments URL's in Facebook posts, and even if Test Pilot is installed or not.
- Activity Stream URL is not displaying an image on Twitter message. 
- Here is a screen recording of the issue: https://goo.gl/jKsOEI.

**Comment by johngruen** [comment] 2017-05-30 11:30
Jeez, how do es this stuff keep breaking when:

* we're using a common template and
* we haven't updated experiment yaml in months

Computers are a pain, let's all move upstate and start a farm.

**Comment by lmorchard** [comment] 2017-08-25 18:57
Think I *might* have figured out the Facebook issue in #2821 - we'll see

As for images not showing up for some experiments on Twitter, while they show up for others: I think I've worked out this one also. 

[We *did* introduce a fix for this about 6 months ago](https://github.com/mozilla/testpilot/commit/1cc53082d333cb8b82049161c8fcf1a5142926d7) - but it requires that all of our images used for social media live in a folder path like this:

`frontend/src/images/experiments/voice-fill/social/`

However, Activity Stream uses images in this path:

`frontend/src/images/experiments/activity-stream/experiments_experiment/e/1/`

The key is the `experiments/{experiment name}/social/` path pattern, which is disabled for cache-busting filename hashing. Otherwise, the URL used in the meta headers for social media links to broken URLs, because those URLs don't get seen by gulp-rev-all, which does the filename hashing

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-30 15:49
I've just tested this on Facebook side and sadly I have obtained mixed results. More bad than good.
However, I won't reopen this yet, we'll retest this week to be sure it's not something temporary or something that needs some time to work right, as we previously experienced with Facebook.

***Using dev links***
- Voice Fill: Wrong image (Test Pilot logo) but has the right text underneath.
- Notes: Wrong image (Test Pilot logo) and wrong text underneath.
- Send: Wrong image (Test Pilot logo) but has the right text underneath.
- Snooze Tabs: Wrong image (Test Pilot logo) and wrong text underneath.
- Containers: Right image but has wrong text underneath.
- Min Vid: Wrong image (Test Pilot logo) but has the right text underneath.

***Using production links***
- Voice Fill: No image and wrong text underneath.
- Notes: Wrong image (Test Pilot logo) but has the right text underneath.
- Send: Right image but has wrong text underneath.
- Snooze Tabs: Wrong image (Test Pilot logo) but has the right text underneath.
- Containers: Right image but has wrong text underneath.
- Min Vid: Wrong image (Test Pilot logo) but has the right text underneath.

Here is a recording of the Facebook results: https://goo.gl/ce7STp.

On Twitter, everything is working well. Haven't tested Activity Stream anymore since the experiment graduated. 
Here is a recording of the Twitter results: https://goo.gl/S1tK9o.

**Comment by lmorchard** [comment] 2017-08-30 16:08
This is definitely not fixed on production yet - we haven't deployed this commit. I'll see if the Facebook spidering for dev is stale - it sometimes caches content for a week or so unless it gets a forced refresh through the debugger

**Comment by lmorchard** [comment] 2017-08-30 20:04
[Per the Facebook debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftestpilot.dev.mozaws.net%2Fexperiments%2Fvoice-fill), it looks like the URLs are fixed on dev. But, per #2691, they're absolute URLs pointing at production. So, we probably won't see fixes for this issue until we've deployed the changes.

![capture](https://user-images.githubusercontent.com/21687/29892513-cfb3d070-8d9c-11e7-90f7-4633fad035fb.PNG)

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-31 09:38
OK, thanks @lmorchard for the clarification. I will recheck them as soon as we deploy to production.

**Comment by SoftVision-PaulOiegas** [comment] 2017-09-22 12:28
We are proud owners of Facebook images and details for each individual experiment. We finally did it, good job guys! 👍 🥇 💐
Verified on both dev and production servers.
![screenshot-2017-9-22 ion ionescu](https://user-images.githubusercontent.com/17258026/30744396-902270f4-9faa-11e7-9246-23d8780e93e0.png)

**Comment by lmorchard** [comment] 2017-09-22 16:53
We did it! https://www.youtube.com/watch?v=SBCw4_XgouA

**Comment by SoftVision-PaulOiegas** [comment] 2017-09-25 08:14
🤣 Good one Les.

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-03 16:06
Sorry guys, I have to reopen this issue since is again reproducible for some experiments. Reproducible on stage and also on production servers.

![screenshot-2017-10-3 cont cosmin](https://user-images.githubusercontent.com/19226534/31135500-d7c09b0e-a86d-11e7-8801-02fd528d4896.png)

**Comment by lmorchard** [comment] 2017-10-04 16:24
That this issue came back is 100% baffling to me. Something is unreliable, either on our end or on Facebook's. But, I can't yet determine what. Trying the Facebook debugger, I got a different result on 3 attempts to debug one of our pages.

Attempt 1: I checked [the Facebook OG debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftestpilot.firefox.com%2Fexperiments%2Fvoice-fill) and saw these warnings and that the last scrape was 9/22 (last deploy was 9/20 and nothing's changed on prod since then):

![capture](https://user-images.githubusercontent.com/21687/31186860-e85aa74e-a8fd-11e7-8b34-5ef74cd8bef4.PNG)

Attempt 2: I viewed source on the Voice Fill page on production and saw that those properties were *not* missing. So, I hit the "Scrape again" button. I got a new warning - a 404 on the Voice Fill social image:

![capture](https://user-images.githubusercontent.com/21687/31186958-42c7e156-a8fe-11e7-9d7a-a3e8825cb422.PNG)

Attempt 3: But, when I checked [the URL to the image](https://testpilot.firefox.com/static/images/experiments/voice-fill/social/vf-fb.jpg), did *not* get a 404 in my own browser. So, I hit "Scrape again" one more time, and everything was fine:

![capture](https://user-images.githubusercontent.com/21687/31187040-86db0d00-a8fe-11e7-9442-b300d4f8fb24.PNG)

I'm not sure what the problem could be on our end, because everything I tried to verify came up okay as expected.

**Comment by johngruen** [comment] 2017-10-04 16:28
@lmorchard @SoftVision-CosminMuntean

**Comment by lmorchard** [comment] 2017-10-04 16:33
Planning to do another production deployment today, so I guess I'll try to keep an eye on if that somehow confuses Facebook 😞

**Comment by lmorchard** [comment] 2017-10-23 16:16
Assigning myself, since I've been troubleshooting it. But, there's no fix that I'm actively working on. Kind of in limbo right now until/unless I can figure out what might be going on

**Comment by chuckharmston** [comment] 2018-03-05 15:50
<img width="533" alt="screen shot 2018-03-05 at 08 49 47" src="https://user-images.githubusercontent.com/23885/36984476-3492f9c4-2052-11e8-8c63-cbc34ddef660.png">

Old issue that doesn't reproduce anymore. Closing!

**Closed as completed by chuckharmston** 2018-03-05 15:50 UTC
Labels: [QA]:Verified fixed, [QA]:Normal issue
