### ISSUE TITLE
Replace all instances of “leave” with “uninstall” to give users’ more peace of mind when opting out of Test Pilot

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#992] opened 2016-06-20 07:37 UTC
From Sharon's UR work. "Leave" == vague. Let's clean up this language.

**Comment by johngruen** [comment] 2016-06-20 08:05
Oh, I already filed this. need to take better notes #986

**Comment by pdehaan** [comment] 2016-06-20 20:10
Closing as dupe of #986 (and assigning that bug to @johngruen).

**Closed as completed by pdehaan** 2016-06-20 20:10 UTC
