### ISSUE TITLE
The experiments tour modal content is wrongly loading in two steps

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3124] opened 2017-12-04 17:34 UTC
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down and click on any active experiments cards (except Send).
3. Click the "Launch Tour" button on left column under "Experiment start date".
4. Observe how the modal content loads.
5. Click on the "Next" arrow and observe again how the modal content loads.

**[Expected result]:**
- The experiment "Tour" modal content is correctly loading without any delays.

**[Actual result]:**
- The experiment "Tour" modal content is loading in two steps, first the written content and after the image which also enlarges the modal.

**[Notes]:**
- This behavior only occurs at first load for each slide of the modal.
- See attached screen recording: https://goo.gl/9z77pr.

**Comment by lmorchard** [comment] 2017-12-04 18:34
This actually sounds like a duplicate of #1477 - but with the added issue of a reflow once the image has loaded. Could at least incrementally improve the situation by establishing the image size before load, so the dialog size doesn't shift

**Comment by meandavejustice** [comment] 2017-12-04 20:33
as a temporary fix I've set the min-height for step-modals (component used by tour and news updates modal) to 400px. It seems to do the trick for now.

**Closed as completed** 2017-12-04 22:00 UTC
Labels: Photonization, [QA]:Verified fixed

**Comment by SoftVision-PaulOiegas** [comment] 2017-12-05 13:04
@lmorchard #1477 is a bit different and it still occurs now that Dave fixed this one.
However, there is still a bit of a jump inside the modal after the image loads, but it's way better than before. 👍  #1477 will fix the remaining problem when implemented.
