### ISSUE TITLE
details-image(s) don't update

### ISSUE THREAD

**Issue by rickycodes** [mozilla/testpilot#2201] opened 2017-02-16 17:00 UTC
Hopefully this isn't a dupe!

**steps to reproduce:**

1. go to an experiment on testpilot.firefox.com in the Chrome browser, eg: https://testpilot.firefox.com/experiments/tab-center (take a note of the preview images):

![screen shot 2017-02-16 at 11 52 53 am](https://cloud.githubusercontent.com/assets/675259/23031532/4f06c9e2-f43f-11e6-9a72-81e7ffd71238.png)

2. navigate to another experiment from the area just below "Try out these experiments as well":

![screen shot 2017-02-16 at 11 56 45 am](https://cloud.githubusercontent.com/assets/675259/23031544/58f7bb1e-f43f-11e6-8849-89173998e5a2.png)

3. the content on this page is updated, but the `detail-image(s)` to the right are still from the previous experiment:

![screen shot 2017-02-16 at 11 57 07 am](https://cloud.githubusercontent.com/assets/675259/23031556/64c0bfae-f43f-11e6-9691-9971e67faef2.png)

4. it's worth noting that if you hard refresh you get the intended preview images.

/cc @vladikoff @bwinton

**Comment by vladikoff** [comment] 2017-02-16 19:17
only @pdehaan knows how to fix this 😄

**Comment by pdehaan** [comment] 2017-02-16 20:19
I think this is a dupe of https://github.com/mozilla/testpilot/issues/2097, but since we just did a production push yesterday, I'll take another look since it's definitely very suspicious.
Thanks @rickycodes!

**Closed as completed** 2017-02-17 17:03 UTC
