### ISSUE TITLE
Update 'Steps' UI on the landing Page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1066] opened 2016-07-13 14:53 UTC
We've changed the path to installing test pilot, so we need to update the steps we describe on the landing page.

![landing page - base 2x](https://cloud.githubusercontent.com/assets/3323249/16807840/fc133552-48e7-11e6-9fc7-98884902abf9.png)

**Comment by lmorchard** [comment] 2016-07-13 15:27
Dupe of https://github.com/mozilla/testpilot/issues/1041

**Closed as completed** 2016-07-13 15:28 UTC
