### ISSUE TITLE
Cannot access experiment page

### ISSUE THREAD

**Issue by fisherhu** [mozilla/testpilot#2763] opened 2017-08-10 18:08 UTC
Things happened:
- I have seen the containers experiment mentioned in some page
- installed the addon (NO Test Pilot installed yet)
- tested, decided to opt out
- try to find a way to give feedback
- if I understand well I need the test pilot addon (not sure tho)
- installed test pilot
- navigated to the experiment page (https://testpilot.firefox.com/experiments/containers)
- page wont load (completely) just the bars jumping

I have no idea if it is a bug or just some hickup. I will not uninstall anything for awhile, but a few days later I think I will.

FF 54.0.1, windows.

**Comment by Eeems** [comment] 2017-08-10 19:50
Duplicate of #2746 and #2754

**Closed as completed** 2017-08-11 17:17 UTC
