### ISSUE TITLE
Quantum fast Test Pilot Homepage

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2817] opened 2017-08-25 08:41 UTC
**[Notes]:**
- I know you guys want to make Test Pilot website astonishing fast, but I think this is too much. 🤣 

**[Affected versions]:**
- Firefox 55.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the astonishing loading speed of the Test Pilot "Homepage" elements. 

**[Expected result]:**
- All the page elements are fast and correctly loaded.

**[Actual results]:**
- Wow! Such mourn! Very broken!

**[Additional notes]:**
- All the other pages are working properly.
- Attached a screenshot of the issue.

![image](https://user-images.githubusercontent.com/17258026/29706347-4dee209c-898a-11e7-9936-d3dedb4c37b2.png)

**Comment by fzzzy** [comment] 2017-08-25 12:38
Are there any 404s in the console or something? This doesn't happen for me...

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-25 12:54
We have retried also on Windows and Mac OS and it still occurs for us on several machines. Even tried with US proxy set and it still occurs. The 404 page is also affected by this issue.

Regarding console errors, here is a screenshot of the browser console.
![image](https://user-images.githubusercontent.com/17258026/29714885-b271fea8-89ad-11e7-8629-326676673e18.png)

**Comment by fzzzy** [comment] 2017-08-25 14:37
MIME type mismatch, thanks, that helps. No idea why it happens but at least there is an error...

**Comment by lmorchard** [comment] 2017-08-25 19:27
I could reproduce this, but then it seemed fixed after another CircleCI run. I think something might have gone wrong with the CircleCI deployment before this latest one.

**Comment by lmorchard** [comment] 2017-08-28 16:56
Seemed to break again this morning after several fast successive merges to master. Re-built the last CircleCI run, which seemed to resolve things. Weird thing is there were no error messages in my browser console, and none in the CircleCI run. Not sure what's up

**Comment by lmorchard** [comment] 2017-09-07 17:54
Looks like dev is working right now and I can't find any obviously fixable problems with deployment. Going to close this for now. We can reopen or file a new issue if this happens again

**Closed as completed by lmorchard** 2017-09-07 17:54 UTC
