### ISSUE TITLE
Snooze Tabs: Tabs Woke Too Late

### ISSUE THREAD

**Issue by rrrnld** [mozilla/testpilot#2750] opened 2017-08-09 10:16 UTC
I am currently experimenting with the snooze tabs functionality, liking it a lot. I was however suprized when I found that tabs that were supposed to reopen at 11am did not reappear in time but popped back up an hour later. Maybe it's a DST issue?

My system: macOS 10.12.6, Firefox 54, Central European Summer Time (Berlin)

**Comment by lmorchard** [comment] 2017-08-09 16:36
When a tab is snoozed, the alarm is set in units of seconds until it's meant to wake back up. So, if you snooze it for 6 hours from now, a DST time change won't alter that. Might be an issue of what time we display in the pop-up being incorrect in this case

**Comment by gaby2300** [comment] 2017-08-09 18:23
In my case, the snoozed tab woke up 15 minutes late: it was set for 15hs
but woke at 15:15 hs

**Comment by lmorchard** [comment] 2017-08-10 18:20
Oh, also this should be an issue filed on the SnoozeTabs project itself. Looks like maybe a duplicate of https://github.com/bwinton/SnoozeTabs/issues/322 or at least related

**Closed as completed by lmorchard** 2017-08-10 18:20 UTC
