### ISSUE TITLE
test pilot report

### ISSUE THREAD

**Issue by shilow19** [mozilla/testpilot#850] opened 2016-05-14 22:02 UTC
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system 
- [x] Firefox build (Nightly, Developer Edition, Be
  If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new
  ![2016-05-14](https://cloud.githubusercontent.com/assets/19353672/15270893/e1e1a1c8-19fd-11e6-9e8e-2bf755d41e8c.png)
  ![2016-05-14 1](https://cloud.githubusercontent.com/assets/19353672/15270894/e508eb68-19fd-11e6-938d-f05069f1878c.png)
  ![2016-05-14 1](https://cloud.githubusercontent.com/assets/19353672/15270895/e81cb5be-19fd-11e6-902f-b87469ab83b2.png)

**Comment by meandavejustice** [comment] 2016-05-16 15:14
closing as duplicate of https://github.com/mozilla/testpilot/issues/856

**Closed as completed by meandavejustice** 2016-05-16 15:14 UTC
