### ISSUE TITLE
[release] 2018-03-14 on stage

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3420] opened 2018-03-14 18:17 UTC
Please QA stage.

- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
-  Release notes: https://github.com/mozilla/testpilot/releases
- Test at http://testpilot.stage.mozaws.net/

**Comment by chuckharmston** [comment] 2018-03-14 18:26
Of note here, we updated the minimum version of Firefox required to 58. We should make sure to QA all the various related workflows with older Firefox versions.

**Comment by SoftVision-PaulOiegas** [comment] 2018-03-21 14:10
Hey guys,

After our run of the Full Functional suite on the **Stage** server, we had an **85%** pass rate with only known issues found (12%) and several functionality not available (3%).
Here are the test results for the staging server testing performed on Friday and Monday:

### **Legend** ###
&#x1F4D5; - major issue
&#x1F4D9; - normal issue
&#x1F4D2; - minor issue
&#x1F4D7; - fixed and verified issue 

## New Issues ##
1. #3421 - &#x1F4D5; [Graduation] Cliqz experiment wrongly appears to be graduated on March 6th on both dev and stage servers
- &#x1F4D7; The issue was already fixed and verified both on dev and stage.

## Known issues ##
1. #3318 - &#x1F4D2; All strings are shortly displayed in English before they are displayed in Firefox build localization
-Partially fixed by react-router merge, still occurs at refresh, or when first visiting Test Pilot page even from localized browser version.
2. #3340 - &#x1F4D9; Footer links are wrongly overlapping on languages with long words, when resizing the browser window
-A quite easy to encounter issue since it reproduces even on half screen display (tested on 22 inch monitor)
3. #1935 - &#x1F4D9; Footer is wrongly displayed in [en] on non localized pages, while it's correctly localized on the ones that are
-This is a quite old issue that we still have and it's kind of stupid. Using same localization, the footer is correctly localized on homepage, but displayed in Eenglish on non localized pages. We are talking about exact same strings...

&#x1F4D7; We have also verified the `min_version` change to Fx 58. We did compatibility tests on Firefox versions between 54 and 57 on dev and stage servers and we haven't found any issues.

### **Based on testing results we would strongly suggest the next course of actions:** ###
Since the blocking issue was fixed before the release, we would strongly suggest to fix #1935 and #3340 in the next sprints, before finalizing the work on Test Pilot website.

**Comment by SoftVision-PaulOiegas** [comment] 2018-03-21 14:17
Production testing was also performed after deployment was done. The results were close to the stage environment, **86% PASS** rate with **12% FAILED KNOWN** issues and **2% NOT AVAILABLE**.
We have double checked also the `min_version 58` by testing with an Fx 57 build and no issues were encountered.

Marking this as verified.

**Closed as completed** 2018-04-02 16:17 UTC
Labels: [QA]:Verified fixed
