### ISSUE TITLE
Artifacts wrongly displayed before and after the number of participants on Edge browser

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2088] opened 2017-01-27 15:29 UTC
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A Windows 10 PC with Edge browser is available. 

[Steps to reproduce]:
1. Open Edge browser and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Observe the number of participants on each active experiments cards.
3. Click on one of the experiments cards and observe again the number of participants.

[Expected result]:
- Number of participants is correctly displayed on all active experiments cards.

[Actual result]:
- Artifacts are wrongly displayed before and after the number of participants on all active experiments cards.

[Notes]:
- Here are some screenshots
![edge artefacts 2](https://cloud.githubusercontent.com/assets/17258026/22376353/56cef1b0-e4b6-11e6-99b5-15cfbe3d6623.png)
 of the issue:

![edge artefacts](https://cloud.githubusercontent.com/assets/17258026/22376291/11806aee-e4b6-11e6-99f7-11ccf5531dc1.png)

**Comment by johngruen** [comment] 2017-01-27 16:12
I think this is a dupe of #1828

**Closed as completed by johngruen** 2017-01-27 16:12 UTC
