### ISSUE TITLE
Test Pilot Does Not Work on Browse In Private

### ISSUE THREAD

**Issue by Lelouch2** [mozilla/testpilot#1667] opened 2016-10-22 22:53 UTC
Test Pilot add on short cut on the top right of my add on bar. Help please. Thanks

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-24 12:51
Hi @Lelouch2 and thanks for reporting this. This is the intended behavior for now, Test Pilot and most of the Experiments are not compatible with Private Window. However, we have a tracking issue already for this so I'm closing yours in favor of #1504.

**Closed as completed by SoftVision-PaulOiegas** 2016-10-24 12:51 UTC
