### ISSUE TITLE
'Notes' and 'Send' Complements impossible to install 

### ISSUE THREAD

**Issue by aaroncadillac** [mozilla/testpilot#2754] opened 2017-08-09 17:36 UTC
My firefox

```
Nombre 	Firefox
Versión 	55.0
Id. de compilación 	20170808130316
Historial de actualizaciones 	
Agente de usuario 	Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
OS 	Linux 4.12.4-1-ARCH
Directorio del perfil 	
Plugins activados 	about:plugins
Configuración de compilación 	about:buildconfig
Uso de memoria 	about:memory
Rendimiento 	about:performance
Service Workers registrados 	about:serviceworkers
Ventanas multiproceso 	1/1 (Habilitado por el usuario)
Web Content Processes 	3/7
Clave de Google 	Encontrada
Clave del servicio de localización de Mozilla 	Encontrada
Modo Seguro 	false
Perfiles 	about:profiles
```
and Notes & Send install pages not load, I found what looks like an error in an event

    TypeError: e is null[Saber más]                                                        vendor.8b61e861.js:1:1
    s                                             https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:1
    r                                    https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:494691
    o                                   https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:494899
    perform                        https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:535358
    batchedUpdates          https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:491707
    batchedUpdates          https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:517057
    dispatchEvent              https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:495984
    dispatchEvent                                                                       self-hosted:987:17
    r                                   https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:392683

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-10 14:40
Hi @aaroncadillac and thanks for your report. However, this is a known issue and it's tracked under #2746. Please follow the thread and provide any additional info there.
We are currently trying to debug the problem trough the users that are reproducing this since we cannot reproduce it on our environments.

I will close this issue as a duplicate in favor of the one mentioned above, but I want to try one thing first on your environment if you would like to help us. 
Please follow the next steps:
1. Navigate to "about:addons" page.
2. Select the "Extensions" tab.
3. Click the cog wheel on top right and click on the "Check for Updates" option. 

Let me know if the Test Pilot add-on is updated and if the https://testpilot.firefox.com loads afterwards. You may have an older version of the add-on that could create this issue.

Thanks.

**Comment by johngruen** [comment] 2017-08-21 16:37
@aaroncadillac We believe this has been fixed. Can you test again?

**Comment by aaroncadillac** [comment] 2017-08-22 04:01
Great! It Works

**Closed as completed** 2017-08-22 07:53 UTC
