### ISSUE TITLE
Visiting site in iOS Firefox shows errror message

### ISSUE THREAD

**Issue by mgaudet** [mozilla/testpilot#3169] opened 2017-12-30 14:14 UTC
... instead of saying “can’t install test pilot extensions on iOS”

**Comment by johngruen** [comment] 2018-01-04 13:17
I'm seeing this too. Per our support matrix we should be supporting FXiOS

**Comment by fzzzy** [comment] 2018-01-04 13:57
Yes, this has been a bug for a long time. What happens is that we see that the browser is Firefox, but then mozAddonManager is not available, so we get confused about that.

**Comment by SoftVision-PaulOiegas** [comment] 2018-01-04 14:15
Dupe of #2642

**Comment by johngruen** [comment] 2018-01-08 17:43
Hey @mgaudet we are gonna fix this one this week, but we'll track it in #2642.

**Closed as completed by johngruen** 2018-01-08 17:43 UTC
Labels: bug
