### ISSUE TITLE
Loop incapablity

### ISSUE THREAD

**Issue by Gaberboo** [mozilla/testpilot#2300] opened 2017-03-10 04:10 UTC
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
mid vid will glitch out when you right click and hit "loop" on youtube videos(I haven't tested this on other video services) it will glitch out when the video ends, it will glitch even more if you click replay after that

**Comment by meandavejustice** [comment] 2017-03-10 17:08
Dupe of https://github.com/meandavejustice/min-vid/issues/622

**Closed as completed** 2017-03-10 17:08 UTC
