### ISSUE TITLE
1-click install of TestPilot and PageShot doesnt install PageShot toolbar icon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2057] opened 2017-01-24 22:12 UTC
Found in https://testpilot.dev.mozaws.net/__version__ (e3c0b4e29dc8dbd692f32a2e000a9af080a18799):

```json
{ "commit": "e3c0b4e29dc8dbd692f32a2e000a9af080a18799",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/2754" }
```

---

### Steps to reproduce:
1. In a new profile, go to https://testpilot.dev.mozaws.net/experiments/page-shot
1. Make sure your `testpilot.env` config variable is set to "dev" in about:config.
1. Click the shiny green "Install Test Pilot and Enable ⁨Page Shot⁩" button to install both Test Pilot and Page Shot experiment.

### Actual results:
Page Shot is installed and enabled in "about:addons" (Page Shot 4.3.201701052116), but I don't see any Page Shot icon in the toolbar, which makes it impossible to use.

### Expected results:
Page Shot icon should appear in my main toolbar

---

![add-ons_manager_and_new_issue_ _mozilla_testpilot](https://cloud.githubusercontent.com/assets/557895/22269167/21ab5b46-e23f-11e6-9d25-2dbb28aad89d.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/22269146/0da087c0-e23f-11e6-8e3c-3d542a07f00c.png)

**Comment by chuckharmston** [comment] 2017-01-24 22:14
I believe this is a dupe of https://github.com/mozilla-services/pageshot/issues/2123

**Closed as completed by chuckharmston** 2017-01-24 22:14 UTC
