### ISSUE TITLE
Tab Center pushes findbar UI (for find-in-page) completely out of view, if you have bookmarks toolbar and/or menubar enabled

### ISSUE THREAD

**Issue by dholbert** [mozilla/testpilot#760] opened 2016-05-10 20:08 UTC
STR:
1. Enable Tab Manager test pilot experiment.
2. Enable bookmarks toolbar and/or menubar (by right-clicking somewhere on your browser toolbar, e.g. on the hamburger menu, and choosing "Menu Bar" and "Bookmarks Toolbar")
3. Visit some web page, e.g. this github page. 
4. Ctrl+F (or Cmd+F on Mac) to activate Find-In-Page bar.

ACTUAL RESULTS:
The find-in-page bar is partially or completely invisible. (If you've only added one of the toolbars in step 2, the very top of the bar might be visible.)

EXPECTED RESULTS:
The find-in-page bar should be visible.

This presumably applies to any other bars at the bottom of the screen. (I believe we have some other notifications that appear down there.)

I'm using latest Firefox Nightly, version 49.0a1 (2016-05-10)

**Comment by serafeimg** [comment] 2016-05-10 20:36
Same issue with version 46.0.1.
The problem is with all the bars as well the end of every web site. 
Issue only solved in full screen mode.

**Comment by pdehaan** [comment] 2016-05-10 20:46
Closing. Filed upstream in **Tab Center** repo: https://github.com/bwinton/VerticalTabs/issues/146

**Closed as completed by pdehaan** 2016-05-10 20:46 UTC
