### ISSUE TITLE
Dev does not install cleanly on a new profile

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1076] opened 2016-07-15 20:18 UTC
Seen on d23bbae520aeff6

Steps to reproduce:
- Create a clean profile
- go to testpilot.dev.mozaws.net
- Install Test Pilot

RESULT:
Add-on appears to install then UI remains in installing state and page does not redirect

EXPECTED:
Add-on installs and site redirects to /experiments

Noticed this error in the console: 
`Unhandled promise rejection waitForMessage timeout: sync-installed` from within the vendor bundle

**Comment by lmorchard** [comment] 2016-07-15 20:20
Looks like a dupe of #1075

**Closed as completed by lmorchard** 2016-07-15 20:20 UTC
Labels: critical
