### ISSUE TITLE
Experiment "Now Active" and checkmark not shown in menu although experiment is active

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/testpilot#926] opened 2016-05-26 17:06 UTC
I guessing this an issue with testpilot not activity stream...

I clicked the testpilot menu item after seeing an email that activity stream had been updated. I can see the list of experiments, it shows the universal search is active (and it is), tab center is not active (and it isn't), but activity stream shows it is not active (but it should be). 

<img width="563" alt="screen shot 2016-05-26 at 12 57 02 pm" src="https://cloud.githubusercontent.com/assets/2964961/15583104/494b24a4-2342-11e6-8d78-5970641122d9.png">

I then clicked "View All Experiments" to load the test pilot site which correctly shows that activity stream and universal search are active. This seemed to have refreshed the menu list as it now shows everything correctly...

<img width="652" alt="screen shot 2016-05-26 at 1 03 54 pm" src="https://cloud.githubusercontent.com/assets/2964961/15583112/5525fc22-2342-11e6-8f79-ba6d39478ee0.png">

Obviously it was in some weird state, possibly related to the activity stream update? Experiment updates should trigger a refresh of the active states perhaps?

**Comment by pdehaan** [comment] 2016-05-26 17:23
Dear @stuartphilp,

I think this is a dupe of #723; **Update doorhanger `Active` state on enablement without a refresh**
Closing.

Sincerely,
@pdehaan

**Closed as completed by pdehaan** 2016-05-26 17:23 UTC
