### ISSUE TITLE
dev site tries to install older version of the testpilot addon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#407] opened 2016-02-10 22:29 UTC
I was trying to verify something on idea-town-dev.elasticbeanstalk.com and noticed I wasn't logged in, so I ran through the flow again and it took me to the point where I have to install the Test Pilot Add-on and it's currently giving me a 404 and pointing at an old (and non-existent) .XPI file.

![test_pilot_-_help_build_firefox_and_2__pdehaan_pdehaan____dev_github_idea-town__zsh__and_3__pdehaan_pdehaan____dev_loads-web-react__zsh_](https://cloud.githubusercontent.com/assets/557895/12963962/5953f53a-d002-11e5-9843-b48a36c9c879.png)

Currently the only XPI in the [/addon/dist/](https://github.com/mozilla/idea-town/tree/master/addon/dist) folder is testpilot-addon-0.3.3.xpi.
I'm trying to track down where we may be setting "idea-town-addon-0.2.1.xpi" to see if there is an easier way to specify the current package.json version for the /addon/dist/*.xpi file.

**Comment by lmorchard** [comment] 2016-02-11 15:34
I think this might basically be a dupe of #244? In a nutshell, the "Install the Add-on" link is known not to work right now, and you have to manually install the XPI.

We don't have a solution for hosting of the main addon worked out - that's #92. The build in github is just for dev convenience and we definitely shouldn't lean on it for anything serious from the site itself. In fact, it should go away after #92.

FWIW, the XPI URL on the site is manually configured in the server env vars - in this case in Elastic Beanstalk app config. Also, there's a possibility we may shut down that environment (#404)

**Comment by meandavejustice** [comment] 2016-02-11 19:02
closing as dupe

**Closed as completed by meandavejustice** 2016-02-11 19:02 UTC
