### ISSUE TITLE
Going to the Test Pilot brings up a blank page

### ISSUE THREAD

**Issue by dedwarmo** [mozilla/testpilot#902] opened 2016-05-24 16:33 UTC
When I try to go to https://testpilot.firefox.com/ I just get a blank white page after the loading animation stops (the blue circle-type-thing that rotates where the website icon appears on the tab).  If I hit refresh it will sometimes load the page.  Sometimes after one refresh the page is still blank.  After the second refresh it almost always loads.
- [Mac OS X 10.11.3 ] Operating system
- [ Firefox 46.0.1] Firefox build (Release)

---

**Comment by pdehaan** [comment] 2016-05-24 16:59
@dedwarmo Thanks for the bug report!
I think you're seeing the elusively intermittent #755 issue.
We're currently investigating and trying and find out why it is happening.

Closing this as a duplicate of #755.

**Closed as completed by pdehaan** 2016-05-24 16:59 UTC
