### ISSUE TITLE
"Settings" menu is missing on legal+about pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3160] opened 2017-12-22 19:55 UTC
Found in 17c86e7b049c78b8cbebdfef1fa46801d99183f4

```json
{
  "commit": "17c86e7b049c78b8cbebdfef1fa46801d99183f4",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/6427"
}
```

---

### Steps to reproduce:
1. Go to homepage; https://testpilot.dev.mozaws.net/.
    **Note:** The header area shows "News Feed", "Blog" and "Settings" (if you have add-on installed).
1. Go to about page; https://testpilot.dev.mozaws.net/about (via the footer).
    **Note:** The header area shows no subnav.
1. Go to Privacy page; https://testpilot.dev.mozaws.net/privacy (via the footer).
    **Note:** The header area shows no subnav.
1. Go to Terms page; https://testpilot.dev.mozaws.net/terms (via the footer).
    **Note:** The header area shows no subnav.
1. Go to experiment details page; https://testpilot.dev.mozaws.net/experiments/send.
    **Note:** The header area shows the subnav again (same as step 1 above).

### Expected results:
The subnav should be consistent and show subnavigation on all pages for consistency.

**Comment by SoftVision-PaulOiegas** [comment] 2018-01-04 12:33
That was by design as far as I remember. We never had the settings button on the pages from footer. But yeah, it could be an improvement if you guys consider them to be useful on those pages. 

On dev the news feed and blog buttons are already there, only the settings button is missing.

**Comment by meandavejustice** [comment] 2018-01-09 16:53
notes from #3164 

> 
    - added news feed and blog links to header of legal pages
    - still doesn't add settings/submenu when logged in on these pages,
    not sure if this is necessary.

adding a `needs:UX` tag to see if the setting/submenu is neccessary on these pages

cc/ @johngruen @ChenMorpheus

**Comment by ChenMorpheus** [comment] 2018-01-10 09:28
@meandavejustice @pdehaan You can refer to #2867 for the prototype, but I created an overview below as well. The reason we decided to remove the settings was to move them to the footer to keep it consistent with the current Firefox websites, such as AMO, Mozilla, etc. I saved the options which we want to promote, or which can introduce some significant information in the header to attract more users, and decided to move items, which no much users visited, to the footer. For about/privacy/terms page, please just follow the header of the homepage. Let me know if any questions, thanks. 

![group 2](https://user-images.githubusercontent.com/18019946/34764172-92142400-f628-11e7-967c-e1b09691cb5f.png)
![group 3](https://user-images.githubusercontent.com/18019946/34764171-91e44c3a-f628-11e7-8e94-d00473e8dc6b.png)

**Comment by chuckharmston** [comment] 2018-03-05 18:56
Closing as a dupe of #2867.

**Closed as completed by chuckharmston** 2018-03-05 18:56 UTC
