### ISSUE TITLE
The experiment logos are no longer displayed on homepage and experiments details page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2428] opened 2017-05-16 09:23 UTC
[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net/".
2. Observe the experiments cards.
3. Click one of the available experiments.
4. Observe the experiment details page.

[Expected result]:
- The experiment logos are correctly displayed on homepage and experiments details page.

[Actual result]:
Step 2: The experiment logos and background color, are not displayed on the experiments cards.
Step 4: The experiment logos are displayed, but the background color is missing on experiment details  page.

[Notes]:
- The experiments color and the logo are correctly displayed on the past experiments cards, but the background color from the past experiments details page is missing.
- Here is a screen recording of the issue: 
![experiment color](https://cloud.githubusercontent.com/assets/19226534/26098976/0e371bfe-3a32-11e7-88c8-2bb0d9fd760b.gif)

**Comment by johngruen** [comment] 2017-05-16 17:22
ah, missed this, will close my dupe

**Comment by fzzzy** [comment] 2017-05-16 20:51
I'm actually working on this in https://github.com/mozilla/testpilot/issues/2434 so I'll close this one as a dupe of that instead.

**Closed as completed by fzzzy** 2017-05-16 20:51 UTC
