### ISSUE TITLE
[release] 2017-03-27 is on Stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2348] opened 2017-03-23 21:41 UTC
Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.

- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases

Current diff from production: https://github.com/mozilla/testpilot/compare/production-static...stage-static

http://testpilot.stage.mozaws.net/

**Comment by SoftVision-PaulOiegas** [comment] 2017-03-27 15:47
Hi guys,

Here is the testing report for the Stage server:
### **New Issues**
1. #2349 - Experiment is not displayed as enabled if you manually enable it from add-ons manager before the Test Pilot add-on is (Normal severity)

2. #2350 - Test Pilot page for installed add-on constantly switches between installed and not installed states, if it's moved to a new window (Normal severity)
- It's not a blocker issue but it highly impacts the UI/UX if you move the Test Pilot tab (installed add-on) to a new window.
3. #2352 - TxP add-ons appear as not installed when moving the Test Pilot web page tab to a new window, while having e10s-multi enabled (Major severity)
- This issue is a major one from end user perspective but its priority is **LOW** due to e10s-multi feature that it's only present in Nightly channel for the moment.

### **Enhancements**
1. #2344 - [Enhancement] The button that informs the user that experiment was manually disabled should redirect to about:addons page
- Since the current implementation uses a button shaped message with hover overlay that does nothing, I was thinking that we could use it to ease the user access to re-enable the experiment.

### **Known issues**
1. #2242 Add "Right Bar" add-on to the list of incompatible add-ons with Tab Center

**Comment by ckprice** [comment] 2017-03-27 20:15
@SoftVision-PaulOiegas we pushed a fix to #2350 to Stage, could you please verify it?

https://github.com/mozilla/testpilot/compare/dac0a9197c59...7338b23c954b

**Comment by SoftVision-PaulOiegas** [comment] 2017-03-28 09:47
@ckprice @fzzzy I've rechecked the behavior described in #2350 and it seems to be fixed. But with this fix, new issues seem to be introduced.  The strange part is that the behavior from #2352 which was only occurring because of e10s-multi on Nightly is now somehow present even on latest Firefox release without enabling e10s-multi (dom.ipc.processCount is set to 1 on Release/Beta/Aurora while on Nightly is at 4).

Here are the observed cases where I've encountered fails:
1. You have TxP + experiment installed. If you move the TxP tab to a new window, a refresh is made and the experiment correctly appears as installed (as expected). However, if you move back the tab from the new window to the old window, the experiment no longer appears as installed and you cannot uninstall TxP either. Exactly the scenario from #2352 only that now it happens when you move the tab back.

Moving it back to a new window, correctly displays again that the experiment is enabled. 

2. You have TxP + Containers installed. Open a new container tab and navigate to a TxP page. If you choose to move the container to a new window from Containers menu, the behavior from #2352 occurs and the experiment is no longer displayed as enabled. 
If you move back the container tab in the main window, this still doesn't fix the experiment state issue.

In my opinion the current fix did more harm than good. We considered #2352 a major issue but with low priority due to e10s-multi. But since now it reproduces also on latest Firefox release, this looks like a change in priority. 
Do you want me to log a new issues for these cases ?

**Comment by fzzzy** [comment] 2017-03-28 11:59
@SoftVision-PaulOiegas Oh no :( I'm not sure we need a new issue for it if you think #2352 covers it -- maybe just add a comment to that issue about it.

**Comment by fzzzy** [comment] 2017-03-28 12:26
I changed my mind, since the str are so convoluted I think it is best to open a new bug.

**Comment by SoftVision-PaulOiegas** [comment] 2017-03-28 13:57
Logged the new behavior in #2356. 
After our IRC discussion, I also tried with e10s disabled on Developer edition browser and the issue still occurs. So I'm not quite sure if this is an e10s issue after all.

@ckprice @wresuolc However, since this looks quite complicated and the fix could take a while, if you guys still want to deploy today, we are ok with it. But only if we are gonna fix this in the next release since it's quite easy to encounter.

**Comment by fzzzy** [comment] 2017-03-28 14:55
We'll do everything in our power to fix it next sprint. Danny's "use mozAddonManager everywhere" branch might help, hopefully we can get that landed in the next few days.

**Closed as completed** 2017-03-31 16:04 UTC
