### ISSUE TITLE
can't install experiments

### ISSUE THREAD

**Issue by bhearsum** [mozilla/testpilot#2777] opened 2017-08-14 13:20 UTC
I get the following two errors in the browser console:
```
Unhandled promise rejection 
TypeError: f.default.Children.map(...) is null
Stack trace:
[object Object]
columnNumber : 131039
fileName : "https://testpilot.firefox.com/static/app/app.e66c374b.js"
lineNumber : 1
message : "f.default.Children.map(...) is null"
stack : "value@https://testpilot.firefox.com/static/app/app.e66c374b.js:1:131039\n_renderValidatedComponentWithoutOwnerOrContext@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:457906\n_renderValidatedComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:458030\nperformInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:453883\nmountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929\nmountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579\nmountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438\n_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842\nmountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074\nmountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579\nmountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438\n_createInitialChildren@https://tes…"
__proto__ : Object { stack: "", … }
vendor.8b61e861.js:27287:12
wrapMethod/e[t]
vendor.8b61e861.js:27287:12
P/</t<
vendor.8b61e861.js:56998:27237
O
vendor.8b61e861.js:56998:26634
P/<
vendor.8b61e861.js:56998:27114
require<["babel-polyfill/browser"]</</<[44]</t.exports
vendor.8b61e861.js:56997:13225
<anonymous>
vendor.8b61e861.js:56997:28017
g
vendor.8b61e861.js:56997:27862
y
vendor.8b61e861.js:56997:27882
(Async: EventHandlerNonNull) require<["babel-polyfill/browser"]</</<[104]<
vendor.8b61e861.js:56997:28185
o
vendor.8b61e861.js:56997:245
o/<
vendor.8b61e861.js:56997:304
require<["babel-polyfill/browser"]</</<[198]<
vendor.8b61e861.js:56998:25994
o
vendor.8b61e861.js:56997:245
o/<
vendor.8b61e861.js:56997:304
require<["babel-polyfill/browser"]</</<[295]<
vendor.8b61e861.js:56999:25010
o
vendor.8b61e861.js:56997:245
o/<
vendor.8b61e861.js:56997:304
require<["babel-polyfill/browser"]</</<[1]</<
vendor.8b61e861.js:56997:569
require<["babel-polyfill/browser"]</</<[1]<
vendor.8b61e861.js:56997:458
o
vendor.8b61e861.js:56997:245
t
vendor.8b61e861.js:56997:420
require<["babel-polyfill/browser"]</<
vendor.8b61e861.js:56997:10
require<["babel-polyfill/browser"]<
vendor.8b61e861.js:56996
i
vendor.8b61e861.js:1:253
r
app.e66c374b.js:1:476
r/<
app.e66c374b.js:1:667
[47]<
app.e66c374b.js:9441:8
r
app.e66c374b.js:1:608
e
app.e66c374b.js:1:787
<anonymous>
app.e66c374b.js:1:373
<anonymous>
app.e66c374b.js:1:312
<anonymous>
app.e66c374b.js:1
TypeError: e is null
[Alamin pa]
vendor.8b61e861.js:1
s
vendor.8b61e861.js:1
r
vendor.8b61e861.js:38847:9
o
vendor.8b61e861.js:38876:27
perform
vendor.8b61e861.js:43428:12
batchedUpdates
vendor.8b61e861.js:38557:13
batchedUpdates
vendor.8b61e861.js:41556:9
dispatchEvent
vendor.8b61e861.js:38956:6
bound dispatchEvent self-hosted:991:17
```

**Comment by lmorchard** [comment] 2017-08-15 17:32
Duplicate of #2746 - a fix is merged but not yet deployed to production

**Closed as completed by lmorchard** 2017-08-15 17:32 UTC
