### ISSUE TITLE
Use SSL on dev site

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1343] opened 2016-09-13 23:33 UTC
Similar to #1329, we should be using SSL on our development site.

I believe the flatfiles move will close this issue, but I'm still filing it as a discrete requirement for our stack in the event that it does not.

**Comment by pdehaan** [comment] 2016-09-14 00:05
Dupe of #548?

**Comment by lmorchard** [comment] 2016-09-14 20:07
Yeah, dupe of #548, but also we have HTTPS via CloudFront here now:

https://testpilot-static.dev.mozaws.net/

**Comment by lmorchard** [comment] 2016-10-03 16:12
Going to close this, since it's done except for changing host names around

**Closed as completed by lmorchard** 2016-10-03 16:12 UTC
