### ISSUE TITLE
Test Pilot button is not displayed in toolbar if the "Never remember history" option is set

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1687] opened 2016-10-26 13:54 UTC
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- The "Never remember history" option from "about:preferences#privacy" is already set on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to testpilot.firefox.com.
2. Click the "Install Test Pilot Add-on" green button and follow the steps to install the add-on.
3. Observe the browser toolbar.

[Expected result]:
- Test Pilot icon is added after installation on the browser toolbar.

[Actual result]:
- Test Pilot icon is not added after installation on the browser toolbar.

[Notes]:
- This issue is also reproducible for most the Test Pilot experiments that are adding a button in toolbar.
- If the Test Pilot experiment page is refreshed, the install Test Pilot add-on option is again available, even if it is already installed.
- Added a screen recording with the issue: https://goo.gl/Q6jwxB.

**Comment by chuckharmston** [comment] 2016-10-26 14:47
That preference sets `browser.privatebrowsing.autostart=true`.

Hm, sounds like a platform issue. Checking with the addons team to see if this is expected.

**Comment by chuckharmston** [comment] 2016-10-26 14:51
I wouldn't actually be surprised if it is expected; it looks like that preference effectively sets private browsing mode for all windows, and [neither Test Pilot nor most experiments](https://github.com/mozilla/testpilot/issues/1504#issuecomment-254512221) are asking to work in private mode.

Great catch, @SoftVision-CosminMuntean.

**Comment by chuckharmston** [comment] 2016-10-26 15:17
Yeah, this is expected behavior for add-ons that haven't opted-in to private browsing mode. Closing in favor of #1504

**Closed as completed by chuckharmston** 2016-10-26 15:17 UTC
