### ISSUE TITLE
 I am in the Test Pilot Program but suddenly cannot enable any of the apps.  Assistance Please!

### ISSUE THREAD

**Issue by pprincetta** [mozilla/testpilot#1498] opened 2016-10-01 02:11 UTC

**Comment by ckprice** [comment] 2016-10-03 17:30
Hi there, thank you for the report! Could you please try to restart Firefox and enable again? This could be related to #1474.

**Comment by pprincetta** [comment] 2016-10-03 18:01
[image: banner_8] http://drprincetta.com/

About http://drprincetta.com/?page_id=439   Services
http://drprincetta.com/?page_id=399   Patient Resources
http://drprincetta.com/patient-resources/   Dr. P's Articles
http://drprincetta.com/?page_id=471   Request Appointment
http://drprincetta.com/?page_id=424   Links
http://drprincetta.com/?page_id=394

I close out Firefox regulary throughout the day.  I did what you suggested
just now and still get this message

Uh oh. ⁨Tracking Protection⁩ could not be enabled. Try again later.

Thank you for helping me

To your health,
Dr. Philip Princetta
www.drprincetta.com http://drprincetta.com/
(619)231-1778

_Maintaining order rather than correcting disorder is the ultimate
principle of wisdom.  To cure disease after it has appeared is like
digging a well when one feels thirsty, or forging weapons after the war has
already begun._ Nei Jing (2nd century BC)

THE GREATEST AND MOST HONORABLE COMPLIMENT ARE YOUR _REFERRALS_---THANK YOU!

**Comment by pprincetta** [comment] 2016-10-04 16:38
Any news on how I can get this to work

**Comment by Foxfan100** [comment] 2016-10-05 10:38
I too have this problem with every Test Pilot item that I try to install. I use Kaspersky AV, and have tried disabling this. However, I note that when I first signed up for Test Pilot, I was able to activate Activity Stream, and this remains the only experiment that I have been able to install and make work.

**Comment by pprincetta** [comment] 2016-10-05 13:30
If someone gives advise please pass it onto me

**Comment by chuckharmston** [comment] 2016-10-05 15:13
As Cory noted, this is likely a duplicate of https://github.com/mozilla/testpilot/issues/1474. I'm going to close this in favor of that issue.

**Closed as completed by chuckharmston** 2016-10-05 15:13 UTC
