### ISSUE TITLE
Blank page after login

### ISSUE THREAD

**Issue by ckarlof** [mozilla/testpilot#827] opened 2016-05-12 18:31 UTC
It's intermittent. 

<img width="1542" alt="screenshot 2016-05-12 11 29 26" src="https://cloud.githubusercontent.com/assets/2365255/15225834/126dff1e-1835-11e6-9957-e2b862af8867.png">

**Comment by ckarlof** [comment] 2016-05-12 18:32
I'm running Nightly 49 with TP enabled.

**Comment by johngruen** [comment] 2016-05-12 18:48
Yes, I've been seeing this too, no experiments installed

**Comment by johngruen** [comment] 2016-05-12 18:50
Got a screenshot...nothing enabled.

![screen shot 2016-05-12 at 2 49 50 pm](https://cloud.githubusercontent.com/assets/3323249/15226464/d00f8144-1850-11e6-8a00-ad0c1cee1487.png)

**Comment by johngruen** [comment] 2016-05-12 18:51
![screen shot 2016-05-12 at 2 50 50 pm](https://cloud.githubusercontent.com/assets/3323249/15226503/f91a6fcc-1850-11e6-8c1e-8c81337d4b08.png)

**Comment by pdehaan** [comment] 2016-05-12 19:07
@ckarlof @johngruen Thanks for the report.
I reckon this is a dupe of #755.

**Closed as completed by pdehaan** 2016-05-12 19:07 UTC
Labels: bug
