### ISSUE TITLE
Can't enable Min Vid

### ISSUE THREAD

**Issue by bodydisplaynone** [mozilla/testpilot#3087] opened 2017-11-21 08:26 UTC
![image](https://user-images.githubusercontent.com/22660372/33061937-0e8c80de-ce9e-11e7-9ffc-4e031e725fda.png)

![image](https://user-images.githubusercontent.com/22660372/33061955-1db13e74-ce9e-11e7-966b-182a6d6fb9f3.png)

**Comment by SoftVision-CarmenFat** [comment] 2017-11-21 09:12
Hi @bodydisplaynone,
Thanks for reporting this, however it's a dupe of [1127](https://github.com/meandavejustice/min-vid/issues/1127).
A fix already exists and should be pushed in the following days.

**Closed as completed by SoftVision-CarmenFat** 2017-11-21 09:12 UTC

**Comment by meandavejustice** [comment] 2017-11-21 20:37
@bodydisplaynone @SoftVision-CarmenFat Fix was just deployed

**Comment by Softvision-CristinaBadescu** [comment] 2017-11-22 09:21
I can confirm that this issue is no longer reproducible, and Min Vid v0.4.6 can be successfully enabled from the Test Pilot experiment page, using latest Nightly build 59.0a1(2017-11-21), on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
