### ISSUE TITLE
Intermittent white screen error

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1130] opened 2016-07-25 22:49 UTC
This was reported today, and I was able to reproduce. 

From the reporter:

> Once I enabled any test and then disabled them, if I try to do anything by clicking on the tests within the Test Pilot icon in the chrome, I get the following blank page (attached).  The first few times I encountered it, I refreshed the page and it loaded, but now it will not at all.
> 
> I’m using:
> Win10
> Firefox 47.0.1
> If a user enables any of the tests and then disables them, tries to go back to them again it results in this blank screen. I’ve rebooted FF twice and it still persists 

![test pilot_console capture](https://cloud.githubusercontent.com/assets/3323249/17120241/03249a06-5299-11e6-9e5d-8152bdec5ba8.png)

My steps:

Repeatedly access experiment details pages through the add-on leads to occasional white screens. Opening the console, the following message appears eventually

```
waitForMessage timeout: sync-installed
```

![white screen](https://cloud.githubusercontent.com/assets/3323249/17120178/8a448038-5298-11e6-9754-19553642d30b.gif)

**Comment by pdehaan** [comment] 2016-07-25 23:13
Sounds maybe related to earlier #1101 report.

---

Not sure if I'm following the right abyss here, but this looks like it _**may** have been_ addressed in PR #1102 (9e93ddcfbab597dc58ea8e6c5ff40637088fba7c), which was merged 4 days ago, on July 21 (and will be included in the **next** deploy).

The **currently** deployed build in production (https://testpilot.firefox.com/__version__), is from July 15 (8e617b1298ab4827a566e0099bcc284a3713594b).

**Comment by lmorchard** [comment] 2016-07-26 01:39
Yeah, this is a dupe of #1101, we haven't deployed the fix yet

**Closed as completed by lmorchard** 2016-07-26 01:39 UTC
Labels: bug
