### ISSUE TITLE
make experiment view load current version from most recent version in changelog

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/testpilot#716] opened 2016-05-05 17:06 UTC
ActivityStream plans on deploying at least bi-weekly if not more.

It'd be nice if testpilot web app fetched current version from: 
https://github.com/mozilla/activity-streams/blob/master/CHANGELOG.md

**Comment by lmorchard** [comment] 2016-05-05 18:15
I think this is related to / a dupe of #547 - we should expand that issue to include auto-filling & updating as much of the experiment info as we can straight from the add-on's install.rdf, and either have an easy-to-click button or auto-polling to see when experiments change

**Comment by pdehaan** [comment] 2016-05-05 21:05
Yeah, I agree this is a dupe.
I'm +1 on auto-polling each add-on's update.rdf [assuming the django admin has that URL] every 4-6h (or whatever interval isn't offensive) and updating the version number automatically.

Plus, when creating/adding a new experiment, it'd be awesome to extract as much information as possible from the update manifest or XPI.

**Comment by pdehaan** [comment] 2016-05-09 17:48
CLosing as dupe.

**Closed as completed by pdehaan** 2016-05-09 17:48 UTC

**Comment by lmorchard** [comment] 2016-05-09 17:50
Going to say this is a dupe of #547, and we should get around to it
