### ISSUE TITLE
Unable to install the test-pilot add-on on Firefox 52.0b3

### ISSUE THREAD

**Issue by magopian** [mozilla/testpilot#2137] opened 2017-02-07 07:24 UTC
When navigating to https://testpilot.firefox.com/, and clicking on the install button, it animates, but nothing else happens. I've uninstalled the react-devtools addon (which was causing a CSP error), and disabled ublock origin (which was causing a second CSP error), but to no avail.

I don't see anything in the console or in the network tab as a result of clicking on the install button. Here's what I see when I click it:
<img width="860" alt="screen shot 2017-02-07 at 08 22 57" src="https://cloud.githubusercontent.com/assets/167767/22681676/ca9333c6-ed0e-11e6-834c-be04f608da92.png">

What can I do to help you investigate this issue?

**Comment by magopian** [comment] 2017-02-07 09:24
I've just tried in nightly (54.0a1) and I can reproduce the same faulty behavior.

**Comment by SoftVision-CosminMuntean** [comment] 2017-02-07 10:44
Hi @magopian, thanks for reporting this.

I haven't managed to reproduce this issue on Firefox (52.0b3) beta or latest Nightly (54.0a1) build using a clean profile. Test Pilot installs successfully. Even tried to use a localized French build, but the result was the same.

Can you please check in "about:config" if "testpilot.env" string pref is set to "production"? Or if there is a chance that the Test Pilot add-on was manually disabled from "about:addons"?

Also, do you have any anti-virus or firewalls installed? We had a few issues where users could not install the add-on until they temporarily disabled the antivirus.

**Comment by magopian** [comment] 2017-02-07 10:50
Woah, very good pointers, indeed I had the addon already installed and disabled. I'm sorry about that...

I guess I was expecting some feedback of some sorts, or maybe tell me that it was already installed? I don't know.

Should I close this issue, or should it be re-posted somewhere else?

**Comment by SoftVision-PaulOiegas** [comment] 2017-02-07 10:58
Hi @magopian. Glad this helped. The issue is already tracked in #1335 & #2125, and came again in discussion these days. 
I will close this in favor of the one that is already opened. Please follow that thread and add details there if needed. Thanks !

**Closed as completed by SoftVision-PaulOiegas** 2017-02-07 10:58 UTC
