### ISSUE TITLE
Mail pane cut off at bottom

### ISSUE THREAD

**Issue by BridgetSmithSF** [mozilla/testpilot#838] opened 2016-05-12 23:14 UTC
I don't know which add-on is causing it, but when I open a new email pane in gmail—to compose an email—the bottom is cut off, including the Send button. If I expand the pane, enough of the Send button is visible to click. OS is 10.9.5 and Firefox version is 46.0.1.

![truncated mail pane](https://cloud.githubusercontent.com/assets/19335880/15233307/83df0900-185c-11e6-9443-1ba15c46be93.png)

**Comment by pdehaan** [comment] 2016-05-12 23:17
@BridgetSmithSF Thanks for the bug report!
I believe this is a dupe of this **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/105

Closing this in favor of the upstream **Tab Center** issue.

**Closed as completed by pdehaan** 2016-05-12 23:17 UTC
