### ISSUE TITLE
The "Enabled" tag is still displayed on Test Pilot pages after manually disabling or removing an experiment from "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1300] opened 2016-08-29 15:32 UTC
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.  
- Test Pilot add-on was previously installed on the profile. 

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2.  Click on one of the available experiments cards and choose to "Enable" the experiment.
3. Return to Test Pilot main page by clicking the Firefox logo on top left of the page.
4. Observe the enabled experiment state in "Experiments" page, on the Test Pilot button doorhanger and on experiment details page.
5. Navigate in a new tab to "about:addons" page and manually disable / remove the enabled experiment.
6. Observe the experiment state on Test Pilot/Experiments page, on the Test Pilot button doorhanger and on experiment details page.

[Expected result]:
- Step 4: The experiment is displayed on all 3 places with the "Enabled" tag.
- Step 6: The experiment is displayed on all 3 places without the "Enabled" tag.

[Actual result]:
- Step 4: The experiment is displayed on all 3 places with the "Enabled" tag.
- Step 6: The experiment is wrongly displayed with the "Enabled" tag on all 3 places.

[Notes]:
- The "Enabled" tag is still displayed even if page is refreshed or browser is restarted. 

![disabled but enabled](https://cloud.githubusercontent.com/assets/17258026/18839588/35404a38-8414-11e6-93fa-cfa900a333e1.png)

**Comment by lmorchard** [comment] 2016-08-29 19:16
I think this might actually be a dupe of #680 

We don't do useful things with the _disabled_ state of an experiment add-on. We just describe installed as "enabled" to keep things simple.

**Comment by SoftVision-PaulOiegas** [comment] 2016-08-31 08:48
Could be. Filed this one because #680 was referring only to experiment details page. Maybe we should also have an indicator on experiments cards for manually disabled ones. I think that wasn't covered in the designs that John provided there.

**Comment by SoftVision-PaulOiegas** [comment] 2016-09-26 15:09
Just updated this since the behavior widened also to manually removed add-ons. Functionality that used to work before.

**Closed as completed** 2017-03-09 20:25 UTC

**Comment by SoftVision-PaulOiegas** [comment] 2017-03-23 15:28
@fzzzy Just looked over this because I haven't got the chance until now. Hammered it a bit and it works fine, except in one case. I'm not reopening it yet since I'm not sure if this case is a limitation or we haven't taken in consideration this case. Let me know what do you think.

You need to have at least one experiment enabled and Test Pilot.
1. While on test pilot page, open a new tab and navigate to "about:addons" page  
2. First disable the experiment and after Test Pilot.
3. Re-enable the experiment.
4. Choose to enable also the Test Pilot add-on and after shift back to Test Pilot tab.
5. Observe the enabled experiment card.

When test pilot is enabled back, the experiment is not displayed as such until you manually refresh the page. Even if you navigate to its details page, the experiment is still displayed as "Disabled form Add-ons manager".
Here is a screen recording with the issue: https://goo.gl/AOiFkr.

**Comment by fzzzy** [comment] 2017-03-23 18:00
@SoftVision-PaulOiegas Thanks, can you file a new bug for that specific case, put it in insprint, and assign it to me? Thanks again.

**Comment by SoftVision-PaulOiegas** [comment] 2017-03-27 12:40
@fzzzy I've logged this (#2349) last Friday but I totally forgot to assign it to you. Sorry for that.

**Comment by SoftVision-CosminMuntean** [comment] 2017-04-04 16:36
This issue is still reproducible if you have a Test Pilot page opened in a tab and manually remove an experiment from "about:addons". When you return to the Test Pilot page, the removed experiment is still displayed as enabled until the page is refreshed.

I have also noticed on "about:addons" page that after removing an experiment you have an option to "Undo" the action. If you refresh the page, the option disappears and the experiment state is correctly updated and displayed on Test Pilot pages.
So I am not sure if this is a Test Pilot issue or is a browser limitation. @fzzzy should I log a new issue for this? 

Here is a screen recording with the described behavior: https://goo.gl/cii72m

**Comment by fzzzy** [comment] 2017-04-04 21:42
@SoftVision-CosminMuntean I think that sounds different enough to file a new issue. Thanks.

**Comment by fzzzy** [comment] 2017-04-04 22:42
Actually, it looks like further discussion should take place at https://github.com/mozilla/testpilot/issues/2349
