### ISSUE TITLE
Install redirect is really slow

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1189] opened 2016-08-04 20:04 UTC
After installing Test Pilot, the landing page does not redirect for a really long time. I know we have a backstop to redirect after 15 seconds, but that should not be default.

**Expected**
Clean Profile, install testpilot, redirect when install completes

**Actual**
![redirect](https://cloud.githubusercontent.com/assets/3323249/17416647/21d80a8e-5a5d-11e6-9849-683494545f3a.gif)

**Comment by johngruen** [comment] 2016-08-04 20:05
saw this in browser console:

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Thu Aug 04 2016 16:02:17 GMT-0400 (EDT)
Full Message: TypeError: this._addon is null
Full Stack: BrowserAddonActor.prototype.id@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/addon.js:50:5
DSC_setAddonOptions/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1556:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
```

**Comment by lmorchard** [comment] 2016-08-04 20:14
Starting to see this too, but no clue yet why. Seems to have started since we introduced the onboarding tab, [but I didn't think it would affect production](https://github.com/mozilla/testpilot/issues/1162). (So, the onboarding tab might be a red-herring)

The long delay is probably exactly 15 seconds - [because the frontend attempts to contact the add-on 3 times, with a 5 second timeout each time](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js#L70). 

For some reason, [the web frontend detects the presence of the add-on (`navigator.testpilotAddon === true`)](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/landing-page.js#L58) but the add-on doesn't answer messages after installation.

But, for some reason, whatever the issue is gets cleared up on a reload - [which is what the web frontend does](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/landing-page.js#L69) if it fails to contact the add-on after the 3 tries. That's at least better than just showing a white page, which is what it used to do in this case.

Failing a discovery of the original issue, I guess we could reduce the timeouts from 5 to 2 seconds or so. But, that's still just guessing whether or not the add-on got installed by the time it reloads the page.

**Comment by pdehaan** [comment] 2016-08-04 23:42
Would Sentry tell us where the promise error is getting thrown?
Ref: https://github.com/mozilla/testpilot/issues/684

**Comment by pdehaan** [comment] 2016-08-05 00:11
OK, looking into one of my new best friends, [**eslint-plugin-promise**](http://npm.im/eslint-plugin-promise), it looks like we may not be handling promise errors in a few places:

``` sh
/Users/pdehaan/dev/github/mozilla/testpilot/addon/index.js
  124:3  error  Expected catch() or return                  promise/catch-or-return
  124:3  error  Each then() should return a value or throw  promise/always-return
  166:3  error  Expected catch() or return                  promise/catch-or-return
  166:3  error  Each then() should return a value or throw  promise/always-return
  399:5  error  Expected catch() or return                  promise/catch-or-return
  399:5  error  Each then() should return a value or throw  promise/always-return
```

```
plugins:
  - promise

rules:
  promise/param-names: 2
  promise/always-return: 2
  promise/catch-or-return: 2
  promise/no-native: 0
```

**Comment by pdehaan** [comment] 2016-08-05 00:16
... But looking at @johngruen's error stack a bit closer, it _may_ be a red herring, since it seems to be referencing a `this._addon` which I can't locate via `$ git grep`, and the error messages reference  `resource://devtools/...` which seems unrelated.

We should handle our Promises a bit better regardless, but it may not be the direct cause.

🐟

**Comment by dannycoates** [comment] 2016-08-05 17:58
I wonder if this is related to the timing of when `app` is created. The delay from `updateExperiments` might be enough to throw it off. https://github.com/mozilla/testpilot/blob/9702ac94297b5a568acf79fb97fd97eb8f730b8f/addon/index.js#L167

**Comment by lmorchard** [comment] 2016-08-05 18:04
> I wonder if this is related to the timing of when app is created. The delay from updateExperiments might be enough to throw it off. 

Oh, that sounds like a good lead!

**Comment by lmorchard** [comment] 2016-08-05 18:05
I was also starting to think maybe we should reverse the communication here... That is, the add-on waits for a ping from the frontend before sending an experiment list. (And then the frontend waits for a response from the add-on.) 

Maybe the frontend should just listen and wait for a ping, and the add-on sends down a message when it's ready. The frontend can then just react to the info when it gets it.

**Comment by dannycoates** [comment] 2016-08-08 16:37
#1195 _may_ have fixed this

**Comment by lmorchard** [comment] 2016-08-08 18:08
Seems fast-ish on my local dev env, but then I don't think I've quite been able to reproduce this issue locally. Tossed some console.log statements in, and it does end up having to attempt to contact the add-on at least twice before continuing after initial install and that's a surprise. I might end up poking at things a bit here, hopefully along with #352 - assuming I can get a test harness working

**Comment by johngruen** [comment] 2016-08-08 19:49
@dannycoates I can't get a redirect at all on a dev on a clean profile :(

**Comment by lmorchard** [comment] 2016-08-08 20:02
Did you set `testpilot.dev` in `about:config` to `dev` before trying to install?

**Comment by pdehaan** [comment] 2016-08-08 20:03
I'm seeing it stall on testpilot.dev.mozaws.net 

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/17494114/2b8bf960-5d68-11e6-90a5-9846ffa28a51.png)

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/17494132/36c5e232-5d68-11e6-9090-f68e4f53530b.png)

---

Clicking the "X" in the about:addons spits the following message in my Browser Console:

![banners_and_alerts_and_browser_console](https://cloud.githubusercontent.com/assets/557895/17494160/56abf9f6-5d68-11e6-96ae-ff45db4d76a3.png)

**Comment by pdehaan** [comment] 2016-08-08 20:07
> Did you set `testpilot.env` in `about:config` to `dev` before trying to install?

Doh! Yeah, that worked. Sorry, for the noise.

**Comment by lmorchard** [comment] 2016-08-08 20:18
Yeah, I don't think those errors are ours. (Hmm, well except for the reference error maybe)

**Comment by lmorchard** [comment] 2016-08-09 19:25
I can't reproduce this any more on my local env or on dev. [I also wrote an integration test that exercises installation through onboarding](https://github.com/mozilla/testpilot/pull/1218) - which seems to work fine in CircleCI, though that's Firefox on Linux. 

Maybe this is fixed? If not, it would be really interesting to figure out what's different that still causes it in other environments and replicate that in a reproducible test to fix it.

**Comment by SoftVision-PaulOiegas** [comment] 2016-08-10 14:22
Cannot reproduce it either if the right environment is set in about:config pref. Stunning fast even. :smiley:

**Comment by lmorchard** [comment] 2016-08-10 16:27
Hmm, I'm just going to close this and call it fixed for now. It's not waiting on any fix that I've heard anyone has in progress. We can re-open if it rears its head again

**Closed as completed by lmorchard** 2016-08-10 16:27 UTC
