### ISSUE TITLE
The "Test Pilot" toolbar button's badge is wrongly redisplayed after the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#3722] opened 2018-07-09 14:03 UTC
[Affected versions]:
- Firefox 61.0 and above

[Affected Platforms]:
- All Windows 
- All Mac
- All Linux

[Prerequisites]:
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false", "extensions.webapi.testing = true", "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Open the browser and navigate to the "https://testpilot.stage.mozaws.net" page.
2. Install the Test Pilot add-on and click the newly added toolbar button.
3. Close the browser and reopen it with the same profile.
4. Observe the Test Pilot button from the browser toolbar.
 
[Expected result]:
- The button is displayed in the toolbar.

[Actual result]:
- The button is displayed in the toolbar but it has a blue badge.

[Notes]:
- When the button is clicked a second time,  the "utm_content=badged" URL parameter is added to the address even if the button does not have a badge.
- The issue is also reproducible on the Dev server.
- Here is a screen recording of the issue:
![badge still displayed after restart](https://user-images.githubusercontent.com/18304511/42454964-a0d3a4ee-8399-11e8-9d29-e663d9f80dd4.gif)

**Comment by johngruen** [comment] 2018-07-10 11:35
@SoftVision-CiprianMuresan can you see what happens if you roll your system clock forward an hour then repeat your steps?

**Comment by johngruen** [comment] 2018-07-10 12:54
Note, this is verified as not a blocker since shipping the experiments resolves it

**Comment by meandavejustice** [comment] 2018-08-06 16:11
I've had some trouble trying to reproduce this one, @SoftVision-CiprianMuresan have you been able to make this happen with a local build?

**Comment by clouserw** [comment] 2018-08-06 19:49
We think this is fixed in the code now, we were just waiting to push it live for a while.  It should be live now

**Closed as completed by clouserw** 2018-08-06 19:49 UTC
Labels: [QA]:Verified fixed, [QA]:Normal issue

**Comment by SoftVision-PaulOiegas** [comment] 2018-08-07 09:45
I think this will always surface on dev and stage until we release the experiments. It happened before launching Notes mobile and Lockbox and the release fixed the issue. I'm gonna mark this as verified and we'll keep an eye for it.
