### ISSUE TITLE
Windows 10 Edge browser is wrongly rendering some website items

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1761] opened 2016-11-04 16:02 UTC
[Prerequisites]:
- A PC with Windows 10 and Edge browser is needed

[Steps to reproduce]:
1. Open Edge browser and navigate to testpilot.firefox.com
2. Scroll the page and observe Page Shot and Min Vid experiments cards logos.
3. Scroll to the page bottom and observe the Test Pilot bottom process description and install button.
4. Scroll to the top of the page and back to bottom.
5. Observe the bottom process description and install button again. 

[Expected result]:
- Step 2: Page Shot and Min Vid experiments logos are correctly rendered.
- Step 3: Test Pilot process description is correctly rendered.
- Step 5: Test Pilot process description is still correctly rendered.

[Actual result]:
- Step 2: Page Shot and Min Vid experiments logos are missing the gradient.
- Step 3: Puzzle and spaceship images are displayed in black instead of white.
- Step 5: Test Pilot process description and install button disappear.

[Notes]:
- The process description icons and install button reappear if hovered and the text appears if selected.
- recorded video of the issue: https://goo.gl/4GCEDo

**Comment by SoftVision-PaulOiegas** [comment] 2016-11-04 16:39
Just looked over the Mac OS Safari rendering for the Homepage and both Page Shot and Min Vid card logos are missing the fancy gradient exactly as on Edge browser.

![safari edge rendering](https://cloud.githubusercontent.com/assets/17258026/20014006/f18d8922-a2bd-11e6-8b45-c8f0edeeffd8.png)

**Comment by johngruen** [comment] 2016-11-17 13:31
wontfixing the non-gradient thing as graceful degradation...incoming PR should fix SVGs

**Comment by johngruen** [comment] 2016-11-17 13:40
Also, i'm going to file a separate issue for the boxes showing up some places in edge

**Comment by SoftVision-PaulOiegas** [comment] 2016-11-17 15:22
@johngruen I assume Step 5 is not contained in the fix of the svgs from #1827 right ? Asking because I can still reproduce that hide behavior.

![missing description and download](https://cloud.githubusercontent.com/assets/17258026/20395102/75760eae-acea-11e6-91e5-88214b1a73df.jpg)

**Comment by johngruen** [comment] 2016-11-17 15:23
@SoftVision-PaulOiegas yeah, i couldn't reproduce...

**Comment by johngruen** [comment] 2016-11-17 15:24
maybe we could move that into a separate issue

**Comment by SoftVision-PaulOiegas** [comment] 2016-11-17 16:21
@johngruen I will do that. 
However, in order to reproduce it, you need to scroll down until you reach the page bottom, than back up to the top and finally back to bottom again. Magic occurs after. 😆 
We reproduced it today on two machines with Edge browser on Windows 10 (cache cleared).

**Comment by johngruen** [comment] 2016-11-17 16:27
@SoftVision-PaulOiegas was able to repro step 5 eventually, i'm seeing scattered reports of SVG text renderng issues in edge. I wonder if there's an issue with text around svgs 🙄

**Comment by johngruen** [comment] 2017-06-27 19:54
Fixed by the inevitable passage of time

**Closed as completed by johngruen** 2017-06-27 19:54 UTC
