### ISSUE TITLE
We need to bring back loading states while pages complete rendering

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2434] opened 2017-05-16 17:47 UTC
There may be some down-the-road workarounds here, but there appear to be several issues related to removing the Loading state as page components get built. To name a few:

* Colors and icons do not seem to be fetched in time making experiment cards not correctly render color or icon
* The card button state swaps subsequent to page load for installed experiments
* The experiment counts getting fetched causes card heights to change
* the Install CTA button flashes
* On experiment details page does not reflect the correct state when loaded; state changes after you see the content.

There are a lot of small cuts here but the sum total is that the site w/o loading components has significant jank associated with toggling state that damages the overall experience of the site. 
Until we can resolve these conflicts without loaders we should bring them back.

**Comment by fzzzy** [comment] 2017-05-16 18:24
Thanks for such detailed feedback.

**Comment by lmorchard** [comment] 2017-05-16 19:11
> Colors and icons do not seem to be fetched in time making experiment cards not correctly render color or icon

Peeking at this, and I think this is actually a separate issue. I'm seeing these CSP errors on dev rejecting the background colors & images for experiment cards

<img width="963" alt="screenshot 2017-05-16 15 09 00" src="https://cloud.githubusercontent.com/assets/21687/26123724/ea15ad4a-3a49-11e7-86f5-9f056090e90d.png">

And I see this on dev:

<img width="1050" alt="screenshot 2017-05-16 15 13 14" src="https://cloud.githubusercontent.com/assets/21687/26123869/827a78c2-3a4a-11e7-8061-9879d286c3b5.png">

**Comment by lmorchard** [comment] 2017-05-16 19:54
Just submitted a PR to reproduce my last comment on local dev, and change CSP to allow inline styles because ugh.

**Comment by lmorchard** [comment] 2017-05-16 19:59
Ah, looks like that was #2432 - which turns out to be CSP related, not time related, and won't be fixed by a loading delay

**Closed as completed** 2017-05-16 21:11 UTC
