### ISSUE TITLE
Wrong cards in list after clicking a card

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1698] opened 2016-10-27 02:19 UTC
With no addon, from an experiment page clicking one of the cards navigates to the new experiment but it remains in the 'other experiments' section.

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-27 07:36
Hey Danny, this probably a dupe of #1518. If you refresh the page after each selected card, the right content is displayed.

**Comment by dannycoates** [comment] 2016-10-27 22:17
> this probably a dupe of #1518.

I think this is different. 

It looks like this is another side effect of the `TypeError: t is null` reported in #1696

The error appears to be caused by a bad interaction between react and l20n. When I remove the `data-l10n-id` from the installation counter [span](https://github.com/mozilla/testpilot/blob/9fb88ef777019d6a9b43cda2735e8833d7d94feb/frontend/src/app/containers/ExperimentPage.js#L457) the error goes away, GA sends the pageview, and the card list renders correctly.

@lmorchard @chuckharmston any ideas how to work around these two libs fighting over the dom?

**Closed as completed** 2016-10-28 21:05 UTC
Labels: bug
