### ISSUE TITLE
TxP add-ons appear as not installed when moving back the Test Pilot web page tab to the main window (release/beta/dev channels))

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2356] opened 2017-03-28 13:42 UTC
**[Notes]**
- This issue is quite strange since this is almost the same behavior from #2352, but this occurs even without e10s-multi enabled and only when moving the tab back to main window.
- This new behavior may have been introduced by the fix for #2350. 
- Discussed with Donovan on IRC that this could be an e10s issue. But after disabling e10s on developer edition, the issue was still present. 

**[Affected versions]:**
- Firefox release v52.0.1
- Firefox Beta v53.0b5
- Dev edition - 54.0a2

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.  
- Test Pilot add-on was previously installed on the profile. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Navigate to an experiment and choose to enable it.
3. Open a second tab (can be empty).
3. Right click on the Test Pilot tab and choose to move it to a new window.
4. Observe the experiment state.
5. Move back the Test Pilot tab with drag and drop in the original window.
6. Observe again the experiment state.

**[Expected result]:**
The experiment remains in enabled state in both the new and original windows.

**[Actual result]:**
4. The experiment is displayed as enabled in the new window.
6. The experiment is shortly displayed as enabled (~1s) in the original window. But after the content is "refreshed" and the experiment is displayed as disabled..

**[Notes]:**
- Also, if you try to uninstall Test Pilot this won't work. After the uninstall is performed and you click on "Home" button, you are redirected to the Test Pilot page for users with installed add-on.
- It seems that the entire tab from the original window is broken. 
- The issue is bypassed only if you open a new tab in the window.
- Here is a screen recording of the issue: https://goo.gl/ebXPWc.

**Comment by fzzzy** [comment] 2017-04-04 19:52
This seems to be fixed in master. Tested on dev, experiment is properly shown as enabled after all steps to reproduce above.

**Closed as completed by fzzzy** 2017-04-04 19:52 UTC

**Comment by SoftVision-PaulOiegas** [comment] 2017-04-05 08:02
@fzzzy Again, same question. Is this on dev server or on other master ? I can reproduce it with the above steps on dev.

If we're talking about other master, maybe it would be better to leave the issues open until they land on dev server. We are not testing on local since you guys told us that any merge to master will land on dev server in no time...
Otherwise, please provide us some steps on how we can setup on windows to test locally and specify the branches where you guys land the fixes, so we can properly test.
