### ISSUE TITLE
Html elements are wrongly displayed in the "Disclaimer; Limitation of Liability" section from Test Pilot "Terms" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3292] opened 2018-01-25 16:30 UTC
[Affected versions]:
- Nightly 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the browser and navigate to "https://testpilot.firefox.com/terms" page.
2. Scroll down the page until you reach at the "Disclaimer; Limitation of Liability" section.
3. Observe the text.

[Expected result]:
- The text is correctly displayed.

[Actual results]:
- Html elements are wrongly displayed in the text.

[Notes]:
- Here is a screenshot with the issue:
![terms](https://user-images.githubusercontent.com/19226534/35399796-c99751c8-01fd-11e8-8ab5-66a7f6400101.png)

**Comment by divyabaid16** [comment] 2018-01-31 09:19
Can I take up this issue ?

**Comment by SoftVision-PaulOiegas** [comment] 2018-01-31 10:28
Hi @divyabaid16. This issue wasn't marked yet as good first bug, probably it is. But if you think you can manage, go for it! 👍😃

**Comment by divyabaid16** [comment] 2018-02-02 08:38
@SoftVision-CosminMuntean can you please guide me regarding this issue ?

**Comment by SoftVision-CosminMuntean** [comment] 2018-02-02 16:59
For developing guidance maybe the right person to ask would be @fzzzy or @lmorchard.

**Comment by fzzzy** [comment] 2018-02-02 19:20
@divyabaid16 It appears the problem is actually in the legal-docs repository.

https://github.com/mozilla/legal-docs/blob/master/firefox_testpilot_Terms/en-US.md

This file has html in it, but it should not, as it is a markdown file. I believe removing the <div> elements will be enough to fix this. The pull request will need to be made against the legal-docs repo. You can reference this testpilot issue in that pull request.

**Comment by divyabaid16** [comment] 2018-02-03 19:48
Please review the PR.

**Comment by pdehaan** [comment] 2018-02-03 23:17
@fzzzy That seems odd. The markdown in legal-docs hasn't changed in a long time. So either this has been happening a long time, and we never noticed until now, or some behavior has changed in a npm module or config. I can't remember if the original idea of the div+class names was to add additional formatting in the legal templates using CSS. I thought maybe it was some subtle background color or some other frivolous effect.

How are we building those legal pages? Does it use [**react-markdown**](https://github.com/rexxars/react-markdown), or something else? Curious if there is just some flag we can add to have it allow `<div>` tags.

**Comment by pdehaan** [comment] 2018-02-05 19:25
Here's where we're using **react-markdown**: https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/tasks/pages.js#L263

Reading the docs at https://github.com/rexxars/react-markdown#options, I'm not sure if the solution is to override `escapeHtml` and set it to `false`. That doesn't come without risk (albeit a small risk), so we may also need to try tweaking `allowedTypes` array as well so we only allow `div` tags. 

Or a more offensive fix of blindly replacing any `<div .*?>` and `</div>` tags before passing the `source` property.

**Comment by pdehaan** [comment] 2018-02-05 19:32
> I can't remember if the original idea of the div+class names was to add additional formatting in the legal templates using CSS. I thought maybe it was some subtle background color or some other frivolous effect.

See https://github.com/mozilla/testpilot/pull/1013 and https://github.com/mozilla/testpilot/issues/1010 and https://github.com/mozilla/testpilot/pull/1005 for some super old context on the legal formatting. I can't find the origin of **why** we wanted/needed to highlight those 2 specific paragraphs, but I believe @johngruen was speaking w/ legal today about the outstanding legal-docs PR.

**Comment by johngruen** [comment] 2018-02-07 11:42
This has been resolved on the legal side, and is now fixed on prod, stage and dev

**Closed as completed by johngruen** 2018-02-07 11:42 UTC
Labels: [QA]:Verified fixed, [QA]:Major issue

**Comment by fzzzy** [comment] 2018-02-07 13:35
@divyabaid16 Thank you!

**Comment by SoftVision-CosminMuntean** [comment] 2018-02-07 16:28
I have retested this issue and is no longer reproducible. Tested on Test Pilot dev, stage and production servers.
