### ISSUE TITLE
Min Vid

### ISSUE THREAD

**Issue by moonundermood** [mozilla/testpilot#2816] opened 2017-08-25 07:37 UTC
I can't choose my decision and  I can't send my screenshot

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-25 08:22
Hi @moonundermood! Sorry but we cannot understand your issue. From the title it looks like it's something related to MIn Vid. Can you please give us more details about it?

**Comment by moonundermood** [comment] 2017-08-26 02:53
Yes, sorry. I can't move this window. It happens with all videos on YouTube. What should I do?

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-28 13:23
The Min Vid player window can be moved by dragging it from the area between the top buttons.
Here is a recording of of how to do it https://goo.gl/bd2SG5. 

If you still cannot move it, please let us know what operating system are you using, and what version of Firefox, so we can try to reproduce your issue.

**Comment by johngruen** [comment] 2017-11-06 17:59
I am closing this issue, @moonundermood if you are still having difficulties, please add this issue here: 
https://github.com/meandavejustice/min-vid

**Closed as completed by johngruen** 2017-11-06 17:59 UTC
