### ISSUE TITLE
It's impossible to install any of the test-pilot addon lol

### ISSUE THREAD

**Issue by roberj974** [mozilla/testpilot#2774] opened 2017-08-13 09:16 UTC
Hi, felt pretty exited to try out, but I don't seem to able to.
When I click on a project wich is still on course to "get started" i am pointed to webpage that is charging forever...
So I never have the acess to the decription and the instalation link.

And when I click on a passed project, i have the description but you guy don't wan't us to tray them aniway. Which is bad too. 

I have desactivated all of my other extension, dowloaded the test pilot extension still nothing. 
If you sort this out I am still interestested please email me at 
help.1 (at) hotmail.fr (and for the others please don't spam)

Best regards,
JRN

**Comment by pdehaan** [comment] 2017-08-13 15:20
@roberj974 What OS and browser version are you using?
Do you see any errors in your browser console? (Firefox: Tools > Web Developer > Web Console)

**Comment by roberj974** [comment] 2017-08-14 18:46
I am using the last Mozilla on windows 10 insider build n° 16257.1
here is my error log info : 
```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.  (unknown)
Unhandled promise rejection TypeError: f.default.Children.map(...) is null
Stack trace:
value@https://testpilot.firefox.com/static/app/app.e66c374b.js:1:131039
_renderValidatedComponentWithoutOwnerOrContext@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:457906
_renderValidatedComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:458030
performInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:453883
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
performInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:454047
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
performInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:454047
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
mountChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:506438
_createInitialChildren@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:467842
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:466074
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
performInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:454047
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
performInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:454047
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
performInitialMount@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:454047
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:452929
mountComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510579
_updateRenderedComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:457618
_performComponentUpdate@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:457135
updateComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:456413
receiveComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:455530
receiveComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:510973
_updateRenderedComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:457381
_performComponentUpdate@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:457135
updateComponent@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:456413
performUpdateIfNecessary@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:455746
performUpdateIfNecessary@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:511155
a@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:515608
perform@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:535358
perform@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:535358
perform@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:516700
w@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:516877
closeAll@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:535940
perform@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:535438
batchedUpdates@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:491707
s@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:515872
r@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:513511
enqueueSetState@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:514600
require<[359]</r.prototype.setState@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:571379
require<[341]</n.default/</b</l.prototype.onStateChange@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:554579
f@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:615595
require<["redux-promise"]</n.default/</<@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:919901
setLocalizations@https://testpilot.firefox.com/static/app/app.e66c374b.js:1:176427
value/<@https://testpilot.firefox.com/static/app/app.e66c374b.js:1:173645
T/</<@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:724326
T/<@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:724196
c@https://testpilot.firefox.com/static/app/vendor.8b61e861.js:1:684730
  vendor.8b61e861.js:1:386978
TypeError: e is null[Learn More] vendor.8b61e861.js:1:1
```

I have seen few other subject about the same issue it's apparently common...

**Comment by kalse** [comment] 2017-08-17 10:54
I can't install the experiments either. When I click on "Get started" of an experiment I get page that is stuck on loading animation [1], and console in developer tools show the same error message reported above.

Even the Test Pilot Experiments page [2] shows error:

```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.
```

I'm on Window 10 Pro build 15063.540, using Firefox 55.0.2 (64-bit), fresh install with Test Pilot the only addon installed. I used Test Pilot previously (the Containers) but I reinstalled Firefox and now I can't get it to work.

The experiments work for me in Firefox 55.0.1 (64-bit) on Ubuntu 16.04 LTS in VirtualBox.

[1] https://undirigible.com/img/testpilot.jpg
[2] https://testpilot.firefox.com/experiments

**Comment by SoftVision-CosminMuntean** [comment] 2017-08-17 11:02
Probably is the same issue as #2746.
@kalse  can you please navigate to "about:preferences" page, click the "Content" section, then click the "Choose" button from the Languages option and see what languages have you set? 
If you don't have the default en-US language, set it to be the first in the list and see if the issue is still reproducible.

**Comment by kalse** [comment] 2017-08-17 11:09
I just changed the language preferences (I had used en-GB previously) and it solved the issue. Thanks for the help @SoftVision-CosminMuntean :)

**Comment by SoftVision-CosminMuntean** [comment] 2017-08-17 11:17
You're welcome! 
However, the issue is already fixed, but is not deployed on production. It will be deployed soon and then you can change back the language preferences.

**Comment by lmorchard** [comment] 2017-08-17 17:15
This should be fixed on production

**Closed as completed by lmorchard** 2017-08-17 17:15 UTC
