### ISSUE TITLE
Test Pilot Add-on not displaying enabled state for experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1152] opened 2016-07-29 15:42 UTC
seen in the wild on Win 10/nightly:

```
osunick [2:33 PM]  
FYI: 
mmayo [11:30 AM]  
neat

[11:30]  
yeah going to re-enable

[11:30]  
and in doing so, notice a tab center bug

[11:30]  
lol

madhava [11:31 AM]  
welcome to test pilot

new messages
mmayo [11:31 AM]  
menu drop down didn't show it as active (after enabling, of course)
```

**Comment by ckprice** [comment] 2016-07-29 16:04
Sounds like a duplicate of #723.

**Closed as completed by ckprice** 2016-07-29 16:04 UTC
