### ISSUE TITLE
Tab Center could not be enabled.

### ISSUE THREAD

**Issue by ashwin713** [mozilla/testpilot#1536] opened 2016-10-06 14:20 UTC
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by ashwin713** [comment] 2016-10-06 14:24
![firefox test pilot tab center](https://cloud.githubusercontent.com/assets/5374486/19156132/7c1c98e8-8bfe-11e6-9743-4c40f5a885f8.png)

**Comment by SoftVision-CosminMuntean** [comment] 2016-10-06 15:00
@ashwin713 do you have any anti-virus or firewalls installed? Maybe your issue could be also related to firewall or antivirus configurations. We had a few issues where users could not install the experiments until they disabled the antivirus ( #1474).

**Comment by chuckharmston** [comment] 2016-10-06 19:33
Thanks for the report!

As @SoftVision-CosminMuntean mentioned, this is a duplicate of #1474. Closing in favor of that issue.

**Closed as completed by chuckharmston** 2016-10-06 19:33 UTC

**Comment by ashwin713** [comment] 2016-10-07 04:22
I use ubuntu, so I have not installed an anti-virus.

Regards,

Ashwin Jayakumar
(ph:+91-8089883350)

**Comment by SoftVision-CosminMuntean** [comment] 2016-10-07 08:22
@ashwin713  what version of Test Pilot do you have installed? To check this please go to about:addons,  "Extensions" section and click the "More" link next to Test Pilot description.

**Comment by ashwin713** [comment] 2016-10-07 09:37
Regards,

Ashwin Jayakumar
(ph:+91-8089883350)
