### ISSUE TITLE
"View all experiments" button leads to a blank page

### ISSUE THREAD

**Issue by vladikoff** [mozilla/testpilot#1140] opened 2016-07-27 15:50 UTC
- [ ] Operating system: OS X
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release): 47.0.1 Release

---

![blank](https://cloud.githubusercontent.com/assets/128755/17182011/1468ff66-53f0-11e6-9f7a-188d15614095.gif)
### STR
- Clean profile with test pilot. 
- install some experiments, click "View All experiments" in FF Desktop
### Expected
- /experiments should load
### Actual
- empty page, no js errors.

**Comment by lmorchard** [comment] 2016-07-27 17:06
This sounds like issue #1101, but it's weird that you don't see an error in the console. Does the page render after a reload?

**Comment by vladikoff** [comment] 2016-07-27 17:25
> Does the page render after a reload?

No when pressing the "reload" button in Firefox (near the nav toolbar).
No when pressing "CMD+R" using the keyboard.

Yes when pressing "SHIFT+CMD+R" using the keyboard.

**Comment by dannycoates** [comment] 2016-07-29 00:52
I can get the page to alternate randomly between blank and rendered just by repeatedly CMD+R on https://testpilot.firefox.com/experiments?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged

But with devtools open it renders every time (with caching enabled or disabled).

_weird_

With Browser Console open here's a blank one

<img width="913" alt="screen shot 2016-07-28 at 5 25 24 pm" src="https://cloud.githubusercontent.com/assets/87619/17234255/da2a8d2c-54eb-11e6-8388-8d05e8b26869.png">

and a rendered one

<img width="914" alt="screen shot 2016-07-28 at 5 49 43 pm" src="https://cloud.githubusercontent.com/assets/87619/17234259/eecd58fe-54eb-11e6-9375-243b6e002f48.png">

**Comment by johngruen** [comment] 2016-07-29 16:06
@vladikoff @dannycoates can you try to reproduce on our dev instance, we believe this is probably a dupe of #1101 and will be fixed in this train

**Comment by dannycoates** [comment] 2016-07-29 17:03
I can occasionally get the page to _flash_ white for a second on dev, but it doesn't get stuck. 👍

**Closed as completed** 2016-08-01 16:29 UTC
