### ISSUE TITLE
Production TestPilot not working (with FF 45)

### ISSUE THREAD

**Issue by presidentelect** [mozilla/testpilot#1154] opened 2016-07-29 17:41 UTC
Operating system: Windows 7 Professional
Firefox: 45.2.0 ESR

After installing Test Pilot, clicking on one of the add-ons takes me to a blank page.  I also get a blank page if I go directly to testpilot.firefox.com.

I am able to see and enable an add-on if I switch the Test Pilot environment to "Staging (testpilot.mozaws.net)".

**Comment by johngruen** [comment] 2016-07-29 18:58
Hey @presidentelect can you post the console error you're seeing on the blank page. I this may be a dupe of #1101 which should be uplifted to Prod on Tuesday.

**Comment by presidentelect** [comment] 2016-08-01 13:41
I does look like it may be the same issue as #1101.  I'm seeing "waitForMessage timeout: sync-installed".
Also, as I mentioned, I do not see the error when running against "Staging" instead of "Production".
Since #1101 was "closed" I assumed it had already been deployed to production.

**Closed as completed** 2016-08-01 16:29 UTC
