### ISSUE TITLE
TestPilot icons not visible.

### ISSUE THREAD

**Issue by SeaBis** [mozilla/testpilot#1666] opened 2016-10-22 18:32 UTC

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-24 12:25
Hi @SeaBis  and thanks for reporting this. Are you trying to install /enable this on a Private Window ?
Test Pilot and most of the experiments are not compatible with Firefox Private Window. In order to properly test the experiments you will need to work on a normal window.

**Comment by SeaBis** [comment] 2016-10-25 18:25
Using Normal window.  I do not use Private window.  Using Kaspersky Small Office Security version 4.

Best regards,

Glen Bishop  RN rtd. Assoc. Eng. IREE

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-26 11:49
Ok... Then is there a chance that you are using the "Options > Privacy > History >Never remember history" option from Firefox ? We found this case while testing and by doing this you also get no icon in Toolbar.

**Comment by SeaBis** [comment] 2016-10-27 15:39
Thanks Paul. Fixed,

Best regards,

Glen Bishop  RN rtd. Assoc. Eng. IREE

**Comment by chuckharmston** [comment] 2016-10-28 16:13
Dupe of #1504

**Closed as completed by chuckharmston** 2016-10-28 16:13 UTC
