### ISSUE TITLE
Set NODE_ENV=production and don't use minified debug builds of React/Redux

### ISSUE THREAD

**Issue by johannhof** [mozilla/testpilot#1506] opened 2016-10-03 09:09 UTC
If you open the console on https://testpilot.firefox.com/ you get these warnings:

```
"Download the React DevTools for a better development experience: https://fb.me/react-devtools"  vendor.f80539e20abf.js:8:3662
"Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details."  vendor.f80539e20abf.js:1:15099
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.  vendor.f80539e20abf.js:13:7475
```

**Comment by pdehaan** [comment] 2016-10-03 15:27
@johannhof, Thanks for the report. I think this is a dupe of #1349.

**Closed as completed by pdehaan** 2016-10-03 15:27 UTC
