### ISSUE TITLE
Tab Center - Find Bar Strange Behaviour

### ISSUE THREAD

**Issue by aayubkh** [mozilla/testpilot#820] opened 2016-05-12 17:13 UTC
## Bookmarks Toolbar Enabled

Whilst the Bookmars Toolbar is **enabled**, the Find Bar is almost invisible. The current work-around is to set the Windows taskbar to **auto-hide** mode (which of course is not very convenient).
![untitled](https://cloud.githubusercontent.com/assets/7010039/15223499/3ae6c9fe-188e-11e6-8f55-e44bc3ba907e.png)
## Bookmarks Toolbar Disabled

However, it shows normal behaviour and is fully shown when the Bookmarks Toolbar is disabled.
![untitled2](https://cloud.githubusercontent.com/assets/7010039/15223578/9cb04cb4-188e-11e6-878e-18a5fce91693.png)

**Comment by pdehaan** [comment] 2016-05-12 17:15
@guseppiguliano Thanks for the bug report!
I believe this is a dupe of this **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/105

Closing this in favor of the upstream **Tab Center** issue.

**Closed as completed by pdehaan** 2016-05-12 17:15 UTC
