### ISSUE TITLE
Notification bar's "What experiments?" button doesn't seem to do anything

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1817] opened 2016-11-16 01:04 UTC
https://testpilot.dev.mozaws.net/__version__ (4836bf7947f8d0012d8b00b0ece017abcc64d3a2):

```json
{ "commit": "4836bf7947f8d0012d8b00b0ece017abcc64d3a2",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/1771" }
```

---

Clicking the "What experiments?" button doesn't seem to do anything, although it does cause a "TypeError: can't access dead object" error into my Browser Console

![browser_console_and_firefox_test_pilot_and_cliqz_ _schnell-suche_und_tracking-schutz____add-ons_fur_firefox_and_mac_-_apple](https://cloud.githubusercontent.com/assets/557895/20330647/17aeb0dc-ab55-11e6-8e37-0c070fcb6604.png)

**Comment by chuckharmston** [comment] 2016-11-21 15:28
@pdehaan I've been trying to reproduce this all morning, but have been unsuccessful. Any chance you have better STR?

**Comment by SoftVision-PaulOiegas** [comment] 2016-11-21 17:25
Tried to reproduce it also but works for me each time.

**Comment by pdehaan** [comment] 2016-11-21 23:46
I can't get this bar to appear locally. I tried hacking the timeout per https://github.com/mozilla/testpilot/pull/1848 (but not sure if that's even the right place/config).

I say we just close this if nobody else can reproduce it. I'll see if I can get a new profile back into a state where this bar reappears for me so I can try reverifying the button behavior.

**Comment by chuckharmston** [comment] 2016-11-22 00:20
@pdehaan I have instructions for hacking that date without touching the code here: https://github.com/mozilla/testpilot/pull/1800#issue-188793047

I'll close this for now, but please reopen if you can get good STR.

**Closed as completed** 2016-11-22 00:20 UTC

**Comment by pdehaan** [comment] 2016-11-22 01:37
Yeah, tested locally and wasn't able to reproduce.
Easiest/laziest solution seemed to be to hack the addon/lib/no-experiments.js' `shouldShowNotification()` to always return `true` locally:

```js
  shouldShowNotification: function() {
    return true;
  },
```

Clicking that "What experiments?" then just redirects me to http://testpilot.dev:8000/?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-notification&utm_content=no-experiments-installed 👍
