### ISSUE TITLE
JS error loading testpilot.dev.mozaws.net in Pontoon with 3rd party cookies disabled

### ISSUE THREAD

**Issue by mathjazz** [mozilla/testpilot#1999] opened 2017-01-09 14:00 UTC
Something's blocking Test Pilot dev site to load within Pontoon iframe if 3rd party cookies are disabled. The loader never stops loading and the following error is shown in the Console:

```
error DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: https://testpilot.dev.mozaws.net/static/app/app.38ac333e.js:3]
```

**Comment by chuckharmston** [comment] 2017-01-09 15:26
Closing as a duplicate of #1777

Thanks for the report!

**Closed as completed by chuckharmston** 2017-01-09 15:26 UTC
