### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Blackshadowguy** [mozilla/testpilot#912] opened 2016-05-24 20:10 UTC
- [Windows XP ] Operating system

Firefox had flagged the download fire for Firefox test pilot. It said "Are you sure you want to download this file? It might not be safe" and I thought "Thanks for warning me your testpilot files aren't guaranteed to be safe" (is this formatted right?)

**Comment by ckprice** [comment] 2016-05-24 21:00
@Blackshadowguy thanks for the report! And yes, this is formatted perfectly.

I'm closing this as a duplicate of #715 which we are actively working to resolve.

Thanks again!

**Closed as completed by ckprice** 2016-05-24 21:00 UTC
