### ISSUE TITLE
open graph and twitter metadata not in newer in experiments

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1441] opened 2016-09-23 20:28 UTC
Looking at view-source:http://testpilot.dev.mozaws.net/experiments/min-vid and it looks like the `<meta>` tags are Test Pilot generic, not experiment specific:

``` html
<title>Firefox Test Pilot</title>
<meta property="og:title" content="Firefox Test Pilot" />
<meta name="twitter:title" content="Firefox Test Pilot" />

<meta name="description" content="Test new Features. Give us feedback. Help build Firefox." />
<meta property="og:description" content="Test new Features. Give us feedback. Help build Firefox." />
<meta name="twitter:description" content="Test new Features. Give us feedback. Help build Firefox." />

<meta name="twitter:card" content="summary" />

<meta property="og:image" content="http://testpilot.dev.mozaws.net/static/images/thumbnail-facebook.1877727a8303.png" />
<meta name="twitter:image" content="http://testpilot.dev.mozaws.net/static/images/thumbnail-twitter.4658b9c6d56e.png" />
```

&mdash; via view-source:http://testpilot.dev.mozaws.net/experiments/min-vid

---

Conversely, here's what the `<meta>` looks like for Activity Stream:

``` html
<title>Firefox Test Pilot - Activity Stream</title>
<meta property="og:title" content="Firefox Test Pilot - Activity Stream" />
<meta name="twitter:title" content="Firefox Test Pilot - Activity Stream" />

<meta name="description" content="A rich visual history feed and a reimagined home page make it easier than ever to find exactly what you&#39;re looking for in Firefox." />
<meta property="og:description" content="A rich visual history feed and a reimagined home page make it easier than ever to find exactly what you&#39;re looking for in Firefox." />
<meta name="twitter:description" content="A rich visual history feed and a reimagined home page make it easier than ever to find exactly what you&#39;re looking for in Firefox." />

<meta name="twitter:card" content="summary_large_image" />

<meta property="og:image" content="http://testpilot.dev.mozaws.net/static/images/thumbnail-facebook.1877727a8303.png" />
<meta name="twitter:image" content="http://testpilot.dev.mozaws.net/static/images/thumbnail-twitter.4658b9c6d56e.png" />
```

&mdash; via view-source:http://testpilot.dev.mozaws.net/experiments/activity-stream

**Comment by lmorchard** [comment] 2016-09-23 20:39
Dupe of https://github.com/mozilla/testpilot/issues/1434

**Closed as completed by lmorchard** 2016-09-23 20:39 UTC
