### ISSUE TITLE
Footer broken on narrow pages

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3606] opened 2018-06-04 22:37 UTC
<img width="2283" alt="screen shot 2018-06-04 at 6 36 16 pm" src="https://user-images.githubusercontent.com/3323249/40945333-5afea8d0-6826-11e8-8ba3-417690d5e367.png">

**Comment by SoftVision-CosminMuntean** [comment] 2018-06-05 14:43
We already logged this issue in #3597. Considering this I will close this as dupe of it.

**Closed as completed by SoftVision-CosminMuntean** 2018-06-05 14:43 UTC
