### ISSUE TITLE
Testpilot Icon in Firefox automatically added to buttons

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/testpilot#2747] opened 2017-08-08 21:17 UTC
Without doing anything (no restart, nothing) Testpilot just added the Testpilot button to my buttons. It says 'New' even though I've already installed all new experiments. This seems quite unnecessary. Is there any way to not do that for that case?

Edit: actually there was an action, I added another button to the overflow panel through "Customize".

![screen shot 2017-08-08 at 23 15 59](https://user-images.githubusercontent.com/330324/29094983-a3e36a3c-7c8f-11e7-913d-40452f577c42.png)

![screen shot 2017-08-08 at 23 16 53](https://user-images.githubusercontent.com/330324/29094996-aff2de16-7c8f-11e7-80dc-1c67855c51d6.png)

Thanks,
Michael

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-09 12:07
Hi @MichaelKohler and thanks for your report. The "New" label appears when new experiments are launched and stays displayed until you click the Test Pilot button. Installing the new experiments won't make it disappear.

However, do you had the Test Pilot button hidden? If yes, it seems that we may have a regression here. When the Test Pilot add-on gets updated to a new version, it should remain hidden if the user choose so.

We had this issue logged (#2188) but not sure why it was closed without any explicit comment. @dannycoates Any idea why? Is this a limitation?

**Comment by MichaelKohler** [comment] 2017-08-09 12:22
Yes, the button was hidden (removed through "Customize").

**Comment by fzzzy** [comment] 2017-08-09 15:05
@SoftVision-PaulOiegas The cause this time was probably the same as the cause in #2188. Because the add-on changed into a bootstrap addon with an embedded webextension, the id of the button likely changed. I'm not sure what we could have done to avoid this other than not change the id again. If we ever do another big rewrite of the addon (not likely), we should make sure that the id stays the same this time, so this doesn't happen again.

@MichaelKohler Thank you for the report.

**Comment by lmorchard** [comment] 2017-08-10 18:25
> It says 'New' even though I've already installed all new experiments. This seems quite unnecessary. Is there any way to not do that for that case?

Currently, [the logic for the "New" label depends on the last time you clicked the button](https://github.com/mozilla/testpilot/blob/master/addon/src/webextension/lib/browserAction.js#L46). It doesn't track whether or not you've installed experiments. Might be a good idea for us to consider changing it to do that, though. Or, at least, remove the "New" if you visit the site at all regardless of clicking the button. 

Maybe something to add as part of #2325 and/or #2419

**Comment by johngruen** [comment] 2017-08-21 16:38
@MichaelKohler We are going to close this b/c we think this a one-time side effect of migrating to a new add-on architecture. Please let us know if you encounter more problems

**Closed as completed by johngruen** 2017-08-21 16:39 UTC
