### ISSUE TITLE
Dev server is not loading

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2662] opened 2017-07-26 05:41 UTC
https://testpilot.dev.mozaws.net/ is stuck on a waiting loop.

**Comment by pdehaan** [comment] 2017-07-26 06:55
Same for me. I seem to be collecting some 403s for a few *.js files:

<img width="1439" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/28608297-b6097c3e-7194-11e7-8d07-c7081e0716c5.png">

**Comment by johngruen** [comment] 2017-07-26 07:32
@flodolo this seems to be an intermittent problem due to pontoon-triggered rebuilds.

**Comment by johngruen** [comment] 2017-07-26 07:34
Might have to do with this? #2631

**Comment by SoftVision-PaulOiegas** [comment] 2017-07-26 12:35
And dupe of #2634. I think @fzzzy and @lmorchard alerady found a trail on it. However, if you don't care about the Homepage, all the other pages are working. You can go straight to https://testpilot.dev.mozaws.net/experiments for example.

**Comment by fzzzy** [comment] 2017-07-26 14:39
Closing as dupe of #2634.

**Closed as completed by fzzzy** 2017-07-26 14:39 UTC
