### ISSUE TITLE
Unable to submit feedback on TestPilot feedback page

### ISSUE THREAD

**Issue by TDA** [mozilla/testpilot#991] opened 2016-06-16 10:29 UTC
Operating system - MAC OS X 10.11
Firefox build (Nightly, Developer Edition, Beta, Release) 48 - Beta

---

Nothing happens when I click `Next` on the feedback page.
![testpilot](https://cloud.githubusercontent.com/assets/432707/16113750/94d649e8-33b5-11e6-869b-10dba377830a.gif)

**Comment by pdehaan** [comment] 2016-06-16 15:09
@TDA Thanks for the feedback, I believe this is a dupe of #989.
Closing this in favor of the other bug.

**Closed as completed by pdehaan** 2016-06-16 15:09 UTC
