### ISSUE TITLE
investigate l20n/react integration

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1714] opened 2016-10-28 21:03 UTC
In #1712 we fixed a conflict in how l20n and react both modify the dom which could easily happen again elsewhere. We ought to look into a more integrated approach. 

This thread might have some leads: https://groups.google.com/forum/#!topic/mozilla.tools.l10n/XtxHgBEokCA

**Comment by stasm** [comment] 2017-02-23 21:26
Sorry about the trouble l20n has been causing. It was designed to work seamlessly with regular DOM. Turns out that this isn't well aligned with how React works.

I wrote a prototype of a library which uses L20n's low-level API and file format, and integrates tightly into React. I wrote about here: https://groups.google.com/forum/#!topic/mozilla.tools.l10n/eP-Vo9UQz6o

@dannycoates, @chuckharmston, @6a68, @lmorchard -- I'd love to hear your thoughts on this.  Feel free to reply in the newsgroup or ping my on IRC. Thanks!

**Comment by fzzzy** [comment] 2017-04-07 15:34
I think we're ready to move to fluent-react next sprint. @stasm it looks really good, thank you so much. I'll file bugs against the repo there if I encounter any.

**Comment by stasm** [comment] 2017-04-07 16:12
Hey, @fzzzy, I'm very happy to hear this!  What is the timeline of the next sprint?  I'm currently working on a few improvements to fluent-react related to falling back on other languages when translations are missing. I plan to finish by the end of next week.

When Test Pilot moves to fluent-react we will also need to migrate the existing translations to the updated FTL syntax. (Fluent uses a newer version of the syntax than L20n.js does.)  The changes are minimal (https://github.com/mathjazz/testpilot/pull/1/files is an example in a test repo) and we already have a plan for how to use Pontoon to automate them. Our plan was to target the dev cycle of April 25—May 9. Would that work for you?

**Comment by fzzzy** [comment] 2017-04-07 17:30
@stasm I'll start working on it, but I won't plan on it being landed in production until you are ready. April 25-May 9 timeframe is fine. Thanks!

**Comment by stasm** [comment] 2017-04-19 15:20
@fzzzy I've published `fluent-react` 0.3.0 today.  See https://groups.google.com/forum/#!msg/mozilla.tools.l10n/eP-Vo9UQz6o/eh8H6hC9AwAJ for a summary of changes. Can I do anything right now to help you try it out in Test Pilot?

**Comment by fzzzy** [comment] 2017-05-25 17:09
I need to remove our use of dangerouslySetInnerHTML before I can switch over. I think I can use https://www.npmjs.com/package/html-react-parser instead. If anyone has a recommendation for another html to react parser, let me know.

**Closed as completed** 2017-08-01 17:04 UTC
Labels: dev papercut, L10N
