### ISSUE TITLE
Tab Center "Now Active" in menu when when disabled, plus white screen of death.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/testpilot#913] opened 2016-05-25 15:34 UTC
UA: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0"
## What happened?
1. Clicked on the Test Pilot icon to open the menu
2. Noticed that Tab Center had a green check and "Now Active"

Note: Tab Center was not enabled (bug 1?)
1. I clicked on the Tab Center menu item
2. Test Pilot page opened with a white screen of death and JS error (bug 2? related to #755)

![white-screen](https://cloud.githubusercontent.com/assets/400117/15546079/7829bda0-2296-11e6-95c4-933794a6cd56.png)

**Comment by meandavejustice** [comment] 2016-05-25 16:19
Thanks for reporting @alexgibson. Closing as dupe of #869 and #755

**Closed as completed by meandavejustice** 2016-05-25 16:19 UTC
