### ISSUE TITLE
Google Inbox layout problem with Tab Center

### ISSUE THREAD

**Issue by tamasbaksa** [mozilla/testpilot#824] opened 2016-05-12 17:34 UTC
The layout of Google Inbox gets messed up with Tab Center enabled. The bottom ~50px is not seen and not accessible, thus many function of Inbox cannot be used. Please refer to the screenshots.
![ginbox_with-tc](https://cloud.githubusercontent.com/assets/19331932/15224177/47b042fc-1878-11e6-828a-6a6d369ed010.png)
![ginbox_without-tc](https://cloud.githubusercontent.com/assets/19331932/15224182/495f5692-1878-11e6-9275-5a38e1ca9a15.png)

**Comment by tamasbaksa** [comment] 2016-05-12 17:37
Well, it is not only the Inbox, it occurs everywhere, as it is stated in [this issue](https://github.com/mozilla/testpilot/issues/823).

**Comment by pdehaan** [comment] 2016-05-12 17:58
@tamasbaksa Thanks for the bug report!
I believe this is a dupe of this **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/105

Closing this in favor of the upstream **Tab Center** issue.

**Closed as completed by pdehaan** 2016-05-12 17:58 UTC
