### ISSUE TITLE
Box edit add-on and Snooze Tabs and/or Min Vid

### ISSUE THREAD

**Issue by acero74** [mozilla/testpilot#2286] opened 2017-03-06 11:03 UTC
I installed the test pilot and enabled Snooze Tabs and Mid Vid late last week. Once enabled I could no longer open files directly from the Box website using the Box edit add-on. Once I disabled these two add-ons Box edit began working again.

When I attempted to open files I received an authentication error.

- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new

I know nothing about coding, and am don't really even understand the guidelines for reporting to this repository, but thought I should draw attention to this issue.

I really want to be able to use these new add-ons, but I need to be able to use Box edt.

Hopefully, whatever is creating the error can be sorted out.

**Comment by SoftVision-CosminMuntean** [comment] 2017-03-06 15:04
Hi @acero74, thanks for reporting this.

Can you please disable the Snooze Tabs and Min Vid add-ons and enable one at a time in order to figure which add-on is not working with Box Edit? 

I am not sure exactly how to reproduce this issue. I have installed the Box Edit from "https://www.box.com/en-gb/resources/downloads", I have created a new account on "https://www.box.com" and I was able to upload or edit files directly from the Box website. I have tried on latest Firefox release with Snooze Tabs and Min Vid enabled from Test Pilot.

Can you please perform a screen recording of the issue? You can use: "https://screencast-o-matic.com/".

**Comment by acero74** [comment] 2017-03-08 10:43
Hi,
I re-enabled them one at a time, as you suggested and the error has not recurred. I don't know what was causing it initially, but it did seem to be related to one of the two. 

Doesn't seem to be happening now.

Thanks for looking into it for my.

Cheers,
Acero.

**Comment by SoftVision-CosminMuntean** [comment] 2017-03-09 09:30
Thanks for retesting this. Considering the fact that the issue is no longer reproducible I will close it.
@acero74 feel free to reopen the issue if the authentication error reappears when using the Test Pilot experiments and provide more information.

**Closed as completed by SoftVision-CosminMuntean** 2017-03-09 09:30 UTC
