### ISSUE TITLE
Can't install experiments

### ISSUE THREAD

**Issue by valenting** [mozilla/testpilot#2723] opened 2017-08-03 19:57 UTC
I'm trying to opt in to new experiments, but it just gets stuck in "Installing..."

The browser console shows this:

> NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReaderCache.getZip] loader.js:249

which points to this:

http://searchfox.org/mozilla-central/rev/f0e4ae5f8c40ba742214e89aba3f554da0b89a33/addon-sdk/source/lib/toolkit/loader.js#249

This has been the case for a few days. Sorry if this bug has already been reported.

**Comment by lmorchard** [comment] 2017-08-03 20:08
Looks like a duplicate of #2689 (unless you're not on linux)

**Closed as completed by lmorchard** 2017-08-03 20:08 UTC

**Comment by valenting** [comment] 2017-08-03 20:12
Indeed on Linux. Thanks!

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-04 10:34
@valenting Other people mentioned some workarounds for this issue:

1. Turned off sandboxing, everything works. Installing experiments and turning sandboxing back on again works as well.
2. Install Test Pilot and desired experiments on the Firefox release version and after switch back to Nightly on the same profile. This will bypass the Nightly issue.
