### ISSUE TITLE
unable to enable Activity Stream

### ISSUE THREAD

**Issue by haimzelig** [mozilla/testpilot#1528] opened 2016-10-05 15:43 UTC
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-06 16:20
@haimzelig Hello and thanks for the report ! Are you using an antivirus client on your PC ? (Avast, Kaspersky, Nod32 or McAfee). We are having some issues with some antivirus clients that are blocking the experiments installations due to Google Analytics code.  We are currently investigating this to find a fix.
In order to install the experiments you would need either to allow the Google Analytics option or to temporary disable the antivirus client until you install them. Let me know if this worked for you.

**Comment by haimzelig** [comment] 2016-10-06 16:33
Yes, I am running Kaspersky.  Thanks for the tip.

**Comment by ncloudioj** [comment] 2016-10-06 19:31
As a side note, various users have reported this issue in the Activity Stream repo. Can anybody take a look at this please?

**Comment by chuckharmston** [comment] 2016-10-06 19:32
@ncloudioj, a fix is in progress (see #1474, #1537).

Closing this as a dupe of #1474.

**Closed as completed by chuckharmston** 2016-10-06 19:32 UTC
