### ISSUE TITLE
MinVid not queueing selected youtube video

### ISSUE THREAD

**Issue by avliet** [mozilla/testpilot#2974] opened 2017-10-18 17:59 UTC
Often, when I select a video on youtube.com, either to play or to queue, I get:

- a video I did not select
- a video I've already watched
- the video pops up in a new window as the regular youtube.com website, but not the min-vid window

**Comment by Softvision-CristinaBadescu** [comment] 2017-10-19 12:04
Thanks for reporting this, but it seems we have 3 different issues described. I'll reply for each one described in bullets:

1. This is a dupe for a known issue: [#1075.](https://github.com/meandavejustice/min-vid/issues/1075)

2. The second issue may be related to the first one you mentioned, but please log it on the Min Vid repository (https://github.com/meandavejustice/min-vid/issues) in order to investigate it more. When logging it, please provide more info, such as: the Operating System you use in order to reproduce the issue, the Min Vid version and steps to reproduce.

3. Also, please log this issue separate, following the instructions provided from the second issue.

I'm going to close this since is in the wrong repository.

**Closed as completed by Softvision-CristinaBadescu** 2017-10-19 12:04 UTC
