### ISSUE TITLE
Experiment is not displayed as enabled if you manually enable it from add-ons manager before the Test Pilot add-on is

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2349] opened 2017-03-24 08:42 UTC
**[Affected versions]:**
- Nightly 55.0a1

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.  
- Test Pilot add-on was previously installed on the profile and one of the active experiments was enabled. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2.  Open a new tab and navigate to "about:addons#extensions" page.
3. Disable the experiment and after, disable also the Test Pilot add-on.
4. Re-enable the experiment.
5. Choose to re-enable also the Test Pilot add-on and after shift back to Test Pilot tab.
6. Observe the enabled experiment card.

**[Expected result]:**
The experiment card has the "Enabled" green tag displayed.

**[Actual result]:**
The experiment does not appear to be enabled.

**[Notes]:**
- If you navigate to the experiment details page, the "<experiment_name> disabled in Add-ons Manager" button is displayed. But I also encountered cases when I had the "Enable <experiment_name> button displayed instead.
- The "Enabled" tag is displayed if page is refreshed, but not if you navigate trough experiments details pages. 
- Here is a screen recording of the issue: https://goo.gl/AOiFkr.

**Comment by fzzzy** [comment] 2017-04-04 19:45
This seems to be fixed now in master. The web page properly shows each state for each step of the above steps to reproduce.

**Comment by fzzzy** [comment] 2017-04-04 22:41
Maybe not. Trying again a different time gave me different results.

**Comment by fzzzy** [comment] 2017-04-06 19:07
The confusion was due to extensions.webapi.testing needing to be set to true to test the mozAddonManager case. This actually is fixed on dev if that preference is set.

**Closed as completed by fzzzy** 2017-04-06 19:07 UTC
