### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by robbglass** [mozilla/testpilot#2981] opened 2017-10-23 01:07 UTC
I've been extremely disjointed since the disappearance of Group Tabs and hope Containers is a worthy replacement.  

"Containers is activated" appears across the top of Test Pilot page. But how to utilize Containers ?

Multi Account Containers 4.0.3 is listed in my extensions library but its icon does appear in the toolbar.

Thanks !

Rob Glass   Late '15 iMac/OS 10.12.6/FF 56.0
[](url)

**Comment by SoftVision-EmilPasca** [comment] 2017-10-23 11:14
I have tested this issue on Mac OS 10.12 with Firefox Release 56 and with the latest Multi Account Containers(4.0.3) and haven't managed to reproduce it.

@robbglass  when have you first encountered this issue? Did the previous version of Containers(3.1.1) from TestPilot worked? Have you updated the TestPilot version of Containers with the one from AMO and from that point you've started seeing this issue?

I similar issue is already logged on Containers repository https://github.com/mozilla/multi-account-containers/issues/801.
I'm going to close this issue as a duplicate of it. 
Can you please provide the requested information on that thread?

**Closed as completed by SoftVision-EmilPasca** 2017-10-23 11:14 UTC
