### ISSUE TITLE
Handle Opt-out of webExtension Installation

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2697] opened 2017-08-01 14:58 UTC
Currently we do not handle the following case: 

### STR

1. Go to the Voice Fill Experiment Page
2. Click `Enable Voice Fill`
3. On the webExtension Install dialog, click `Cancel`
![screen shot 2017-10-06 at 1 30 54 pm](https://user-images.githubusercontent.com/3323249/31277823-ae5f2918-aa9a-11e7-8989-4ea0bb9e95f2.png)

### Expected

The `Enable Voice Fill` Button should revert to its pre-installed state and an event should be emitted indicating that the user opted out of experiment installation.

```
ec: ExperimentDetailsPage Interactions
ea: Cancel From Permission
el: {experiment title}
```

Additionally in order to understand how cancels compare to installations, we should also record each time a user accepts installation from the permission dialog.

```
ec: ExperimentDetailsPage Interactions
ea: Accept From Permission
el: {experiment title}
```

### Actual

The `Enable Voice Fill` button barberpolls until page reset and the test pilot icon sheds a tear.

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-01 15:36
I have a Mozilla issue on this also, it's on my list to be logged. If you don't select an option on the doorhanger and close the tabs, you'll have an entry in "about:add-ons" page for each install attempt.
Those only disappear at browser restart.
I'll post a link here after I log it.

**Comment by valenting** [comment] 2017-08-03 19:46
Not sure if this is related, but if I set **extensions.legacy.enabled;false** then the testpilot extension is disabled.

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-04 10:31
@valenting yes, because the Test Pilot old add-on was based on SDK and the new add-on didn't landed yet on production server. It will land in the next release probably, if everything is ok from QA perspective.

Anyway, thanks for the heads up! 😃

**Comment by valenting** [comment] 2017-08-04 10:50
Note that if the Test Pilot 'old add-on' is not checked into mozilla-central it will likely be broken in Nightly in the next few days. (It might already be. See [bug 1326520](https://bugzilla.mozilla.org/show_bug.cgi?id=1326520))

From what I understand, the plan is to flip the pref sometime next week. I just want to make sure that the test pilot team is aware of these changes.

**Comment by SoftVision-PaulOiegas** [comment] 2017-08-04 11:58
We are aware, and we already have a new add-on in testing for this matter. Thank you for your concern! 👍 
The pref will be switched starting with 8th of August if I remember well.

**Comment by SoftVision-PaulOiegas** [comment] 2017-09-13 11:12
> I have a Mozilla issue on this also, it's on my list to be logged. If you don't select an option on the doorhanger and close the tabs, you'll have an entry in "about:add-ons" page for each install attempt.
Those only disappear at browser restart.
I'll post a link here after I log it.

I have done some further investigations on this matter and found out that it's only reproducing for Test Pilot experiments. I have logged a separate issue for this in our GitHub #2829.

**Closed as completed** 2017-10-23 21:26 UTC

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-24 13:42
I have retested this issue and is no longer reproducible on Test Pilot dev server. 
After clicking the "Cancel" button the "Enabling..." button is changed back in the "Enable [experiment_name]" button and the "Uh oh. [experiment_name] could not be enabled. Try again later." error is displayed.
Marking this issue as verified.
