### ISSUE TITLE
Two unneeded "Show More" text buttons were implemented on Test Pilot "Privacy" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1651] opened 2016-10-21 09:43 UTC
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.stage.mozaws.net page.
2. Click on the "Privacy Notice" text link under the "Install the Test Pilot Add-on" green button.
3. Observe the "Learn More" text buttons displayed on the page.

[Expected result]:
- There are 2 "Learn More" buttons that expand details about "Data collection" and second "Logs, Cookies, Analytics, etc"

[Actual result]:
- There are 2 extra unneeded "Learn More" buttons on the top part. One close to the date that expands a phrase that should always be there based on designs. And a second one that expands only one title that should also be displayed by default.

[Notes]:
- If the 1st and 2nd "Learn More" sections are expanded, after you close the first one, you end up with the previous expanded title always on the page. You can no longer close it since the 2nd "Show Less" button is now hidden by retracting 1st section.

![unneeded extra text buttons](https://cloud.githubusercontent.com/assets/17258026/19594021/ee1aee2a-978b-11e6-8608-71af9b72383c.png)

**Comment by chuckharmston** [comment] 2016-10-21 10:54
This is (not obviously) a dupe of #1641.

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-21 13:45
Umm... ok. Based on that issue I logged this one. I understood that there were no show less / show more toggles but not that there were to many. 😆 Will re-check after the fix.

**Comment by lmorchard** [comment] 2016-10-21 16:01
Hmm, actually, I think this is an issue... the toggles are back, but now they're kind of overzealous.

**Closed as completed** 2016-10-21 21:43 UTC

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-24 08:58
Overzealous toggles confirmed as fixed. 😆 
One thing bothers me still. I know that by default there is less content on Privacy page than on other pages, but it looks a bit out of order that it starts from the middle of the page. 
On the old implementation (production), it starts from the top.
