### ISSUE TITLE
Small problem with the CSS when the browser window doesn't have focus.

### ISSUE THREAD

**Issue by bwinton** [mozilla/testpilot#1216] opened 2016-08-09 14:30 UTC
Introduced in #1210.

Maybe we can make the selector a little more restrictive?
<img width="103" alt="screen shot 2016-08-05 at 18 39 24" src="https://cloud.githubusercontent.com/assets/159571/17519591/9ec398d6-5e1a-11e6-86f6-91fab0ee3b9a.png">
(Found by @phlsa, reported via Slack.)

**Comment by johngruen** [comment] 2016-08-09 17:42
@bwinton is this a dupe of #1215

**Comment by bwinton** [comment] 2016-08-09 17:44
I don't _think_ so, although depending on how you choose to fix that bug, this might no longer be a problem…

(On Mac, the toolbar icons should be greyer when the window isn't focused, so that's expected behaviour for this platform at least…)

**Comment by dannycoates** [comment] 2016-08-09 17:47
@bwinton are you talking about the blurred text? FWIW badge text has always looked that way when the window is unfocus with the dev edition theme for me. A `text-shadow: none;` seems to fix it.

**Comment by bwinton** [comment] 2016-08-09 17:52
Yeah, well, partially the blurred text, partially the bold background, mostly the way they interact to make it really hard to read.  😉  Could you post a screenshot of what it looked like before your patch (or on a different button)?

**Comment by dannycoates** [comment] 2016-08-09 18:13
<img width="73" alt="screen shot 2016-08-09 at 11 08 43 am" src="https://cloud.githubusercontent.com/assets/87619/17527807/b5307c72-5e21-11e6-9920-fd14defaa72b.png">

On the left is with adding `text-shadow: none;` and the right is no custom style with the color set by `button.badgeColor = '#1996F7'` with the dev edition theme.

**Comment by dannycoates** [comment] 2016-08-11 16:53
i think #1221 fixes this

**Closed as completed by dannycoates** 2016-08-11 16:53 UTC
