### ISSUE TITLE
Testpilot Feedback Page

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#871] opened 2016-05-18 16:50 UTC
This probably just a client side problem, but clicking on next on the feedback page does nothing. I've tried reloading, quitting Firefox and restarting and even resetting Firefox but nothing happens. 
![feedback_page_problems](https://cloud.githubusercontent.com/assets/12704804/15367449/eb01f45a-1cdd-11e6-81ca-192df3c87070.PNG)

**Comment by pdehaan** [comment] 2016-05-18 20:25
@Qhuea Thanks for the bug report!

I believe this is the same issue as #856. We're investigating and will update the other bug when we have more information.

Closing as a dupe of #856.

**Closed as completed by pdehaan** 2016-05-18 20:25 UTC
